const instantNoodles = [
  {
    brand: 'Mama',
    spicinessLevel: 3,
    originCountry: 'thailand',
    rating: 5,
    category: 'Packet Noodles',
  },
  {
    brand: 'Indomie',
    spicinessLevel: 4,
    originCountry: 'china',
    rating: 3,
    category: 'Packet Noodles',
  },
  {
    brand: 'Ottogi',
    spicinessLevel: 5,
    originCountry: 'vietnam',
    rating: 7,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Indomie',
    spicinessLevel: 3,
    originCountry: 'taiwan',
    rating: 3,
    category: 'Cup Noodles',
  },
  {
    brand: 'MyKuali',
    spicinessLevel: 5,
    originCountry: 'taiwan',
    rating: 4,
    category: 'Packet Noodles',
  },
  {
    brand: 'Vifon',
    spicinessLevel: 1,
    originCountry: 'china',
    rating: 10,
    category: 'Cup Noodles',
  },
  {
    brand: 'Paldo',
    spicinessLevel: 1,
    originCountry: 'malaysia',
    rating: 7,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Paldo',
    spicinessLevel: 3,
    originCountry: 'philippines',
    rating: 4,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Samyang',
    spicinessLevel: 5,
    originCountry: 'south_korea',
    rating: 1,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Ottogi',
    spicinessLevel: 4,
    originCountry: 'south_korea',
    rating: 3,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Vifon',
    spicinessLevel: 2,
    originCountry: 'philippines',
    rating: 3,
    category: 'Cup Noodles',
  },
  {
    brand: 'Mama',
    spicinessLevel: 5,
    originCountry: 'vietnam',
    rating: 8,
    category: 'Packet Noodles',
  },
  {
    brand: 'Mama',
    spicinessLevel: 4,
    originCountry: 'malaysia',
    rating: 4,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Nissin',
    spicinessLevel: 1,
    originCountry: 'vietnam',
    rating: 7,
    category: 'Cup Noodles',
  },
  {
    brand: 'TaoKaeNoi',
    spicinessLevel: 5,
    originCountry: 'vietnam',
    rating: 7,
    category: 'Packet Noodles',
  },
  {
    brand: 'TaoKaeNoi',
    spicinessLevel: 2,
    originCountry: 'thailand',
    rating: 7,
    category: 'Cup Noodles',
  },
  {
    brand: 'Vifon',
    spicinessLevel: 1,
    originCountry: 'vietnam',
    rating: 5,
    category: 'Cup Noodles',
  },
  {
    brand: 'Mama',
    spicinessLevel: 2,
    originCountry: 'indonesia',
    rating: 5,
    category: 'Packet Noodles',
  },
  {
    brand: 'Ottogi',
    spicinessLevel: 4,
    originCountry: 'china',
    rating: 3,
    category: 'Cup Noodles',
  },
  {
    brand: 'Ottogi',
    spicinessLevel: 2,
    originCountry: 'indonesia',
    rating: 1,
    category: 'Bowl Noodles',
  },
  {
    brand: 'TaoKaeNoi',
    spicinessLevel: 3,
    originCountry: 'japan',
    rating: 9,
    category: 'Cup Noodles',
  },
  {
    brand: 'Mama',
    spicinessLevel: 4,
    originCountry: 'thailand',
    rating: 2,
    category: 'Cup Noodles',
  },
  {
    brand: 'Samyang',
    spicinessLevel: 5,
    originCountry: 'philippines',
    rating: 1,
    category: 'Packet Noodles',
  },
  {
    brand: 'Mama',
    spicinessLevel: 1,
    originCountry: 'vietnam',
    rating: 10,
    category: 'Packet Noodles',
  },
  {
    brand: 'Nissin',
    spicinessLevel: 1,
    originCountry: 'singapore',
    rating: 7,
    category: 'Packet Noodles',
  },
  {
    brand: 'Samyang',
    spicinessLevel: 4,
    originCountry: 'malaysia',
    rating: 7,
    category: 'Cup Noodles',
  },
  {
    brand: 'MyKuali',
    spicinessLevel: 1,
    originCountry: 'japan',
    rating: 6,
    category: 'Packet Noodles',
  },
  {
    brand: 'MyKuali',
    spicinessLevel: 4,
    originCountry: 'singapore',
    rating: 9,
    category: 'Cup Noodles',
  },
  {
    brand: 'Samyang',
    spicinessLevel: 1,
    originCountry: 'south_korea',
    rating: 1,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Vifon',
    spicinessLevel: 4,
    originCountry: 'china',
    rating: 4,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Nissin',
    spicinessLevel: 5,
    originCountry: 'malaysia',
    rating: 9,
    category: 'Cup Noodles',
  },
  {
    brand: 'Paldo',
    spicinessLevel: 2,
    originCountry: 'south_korea',
    rating: 8,
    category: 'Packet Noodles',
  },
  {
    brand: 'Paldo',
    spicinessLevel: 5,
    originCountry: 'taiwan',
    rating: 3,
    category: 'Cup Noodles',
  },
  {
    brand: 'Vifon',
    spicinessLevel: 3,
    originCountry: 'south_korea',
    rating: 7,
    category: 'Cup Noodles',
  },
  {
    brand: 'Paldo',
    spicinessLevel: 3,
    originCountry: 'japan',
    rating: 4,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Paldo',
    spicinessLevel: 2,
    originCountry: 'taiwan',
    rating: 6,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Mama',
    spicinessLevel: 1,
    originCountry: 'taiwan',
    rating: 2,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Vifon',
    spicinessLevel: 2,
    originCountry: 'china',
    rating: 10,
    category: 'Packet Noodles',
  },
  {
    brand: 'Acecook',
    spicinessLevel: 1,
    originCountry: 'philippines',
    rating: 10,
    category: 'Cup Noodles',
  },
  {
    brand: 'TaoKaeNoi',
    spicinessLevel: 5,
    originCountry: 'philippines',
    rating: 1,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Ottogi',
    spicinessLevel: 1,
    originCountry: 'china',
    rating: 3,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Nissin',
    spicinessLevel: 4,
    originCountry: 'south_korea',
    rating: 6,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Paldo',
    spicinessLevel: 4,
    originCountry: 'indonesia',
    rating: 10,
    category: 'Cup Noodles',
  },
  {
    brand: 'Samyang',
    spicinessLevel: 2,
    originCountry: 'philippines',
    rating: 2,
    category: 'Packet Noodles',
  },
  {
    brand: 'TaoKaeNoi',
    spicinessLevel: 1,
    originCountry: 'vietnam',
    rating: 6,
    category: 'Cup Noodles',
  },
  {
    brand: 'Ottogi',
    spicinessLevel: 2,
    originCountry: 'thailand',
    rating: 1,
    category: 'Cup Noodles',
  },
  {
    brand: 'Paldo',
    spicinessLevel: 1,
    originCountry: 'indonesia',
    rating: 3,
    category: 'Cup Noodles',
  },
  {
    brand: 'MyKuali',
    spicinessLevel: 5,
    originCountry: 'south_korea',
    rating: 7,
    category: 'Packet Noodles',
  },
  {
    brand: 'Paldo',
    spicinessLevel: 5,
    originCountry: 'indonesia',
    rating: 8,
    category: 'Cup Noodles',
  },
  {
    brand: 'Acecook',
    spicinessLevel: 1,
    originCountry: 'japan',
    rating: 10,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Acecook',
    spicinessLevel: 1,
    originCountry: 'indonesia',
    rating: 8,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Acecook',
    spicinessLevel: 3,
    originCountry: 'philippines',
    rating: 7,
    category: 'Cup Noodles',
  },
  {
    brand: 'Vifon',
    spicinessLevel: 2,
    originCountry: 'singapore',
    rating: 3,
    category: 'Packet Noodles',
  },
  {
    brand: 'TaoKaeNoi',
    spicinessLevel: 5,
    originCountry: 'taiwan',
    rating: 10,
    category: 'Cup Noodles',
  },
  {
    brand: 'Ottogi',
    spicinessLevel: 3,
    originCountry: 'singapore',
    rating: 10,
    category: 'Cup Noodles',
  },
  {
    brand: 'Samyang',
    spicinessLevel: 4,
    originCountry: 'indonesia',
    rating: 3,
    category: 'Packet Noodles',
  },
  {
    brand: 'Acecook',
    spicinessLevel: 1,
    originCountry: 'philippines',
    rating: 3,
    category: 'Packet Noodles',
  },
  {
    brand: 'Paldo',
    spicinessLevel: 3,
    originCountry: 'japan',
    rating: 8,
    category: 'Packet Noodles',
  },
  {
    brand: 'Mama',
    spicinessLevel: 3,
    originCountry: 'south_korea',
    rating: 10,
    category: 'Cup Noodles',
  },
  {
    brand: 'MyKuali',
    spicinessLevel: 2,
    originCountry: 'taiwan',
    rating: 7,
    category: 'Packet Noodles',
  },
  {
    brand: 'Indomie',
    spicinessLevel: 2,
    originCountry: 'philippines',
    rating: 4,
    category: 'Packet Noodles',
  },
  {
    brand: 'TaoKaeNoi',
    spicinessLevel: 1,
    originCountry: 'japan',
    rating: 7,
    category: 'Packet Noodles',
  },
  {
    brand: 'Mama',
    spicinessLevel: 4,
    originCountry: 'thailand',
    rating: 1,
    category: 'Cup Noodles',
  },
  {
    brand: 'Vifon',
    spicinessLevel: 5,
    originCountry: 'vietnam',
    rating: 4,
    category: 'Cup Noodles',
  },
  {
    brand: 'TaoKaeNoi',
    spicinessLevel: 4,
    originCountry: 'taiwan',
    rating: 8,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Paldo',
    spicinessLevel: 4,
    originCountry: 'indonesia',
    rating: 8,
    category: 'Packet Noodles',
  },
  {
    brand: 'Samyang',
    spicinessLevel: 3,
    originCountry: 'south_korea',
    rating: 3,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Paldo',
    spicinessLevel: 3,
    originCountry: 'indonesia',
    rating: 10,
    category: 'Packet Noodles',
  },
  {
    brand: 'Ottogi',
    spicinessLevel: 3,
    originCountry: 'thailand',
    rating: 1,
    category: 'Packet Noodles',
  },
  {
    brand: 'Indomie',
    spicinessLevel: 5,
    originCountry: 'south_korea',
    rating: 6,
    category: 'Packet Noodles',
  },
  {
    brand: 'MyKuali',
    spicinessLevel: 4,
    originCountry: 'philippines',
    rating: 6,
    category: 'Cup Noodles',
  },
  {
    brand: 'Ottogi',
    spicinessLevel: 2,
    originCountry: 'japan',
    rating: 8,
    category: 'Bowl Noodles',
  },
  {
    brand: 'MyKuali',
    spicinessLevel: 2,
    originCountry: 'vietnam',
    rating: 6,
    category: 'Bowl Noodles',
  },
  {
    brand: 'MyKuali',
    spicinessLevel: 4,
    originCountry: 'philippines',
    rating: 7,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Samyang',
    spicinessLevel: 5,
    originCountry: 'japan',
    rating: 6,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Paldo',
    spicinessLevel: 1,
    originCountry: 'south_korea',
    rating: 3,
    category: 'Packet Noodles',
  },
  {
    brand: 'Acecook',
    spicinessLevel: 3,
    originCountry: 'vietnam',
    rating: 5,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Paldo',
    spicinessLevel: 2,
    originCountry: 'taiwan',
    rating: 1,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Ottogi',
    spicinessLevel: 5,
    originCountry: 'china',
    rating: 2,
    category: 'Bowl Noodles',
  },
  {
    brand: 'TaoKaeNoi',
    spicinessLevel: 4,
    originCountry: 'japan',
    rating: 1,
    category: 'Cup Noodles',
  },
  {
    brand: 'Indomie',
    spicinessLevel: 5,
    originCountry: 'singapore',
    rating: 5,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Samyang',
    spicinessLevel: 4,
    originCountry: 'indonesia',
    rating: 9,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Indomie',
    spicinessLevel: 2,
    originCountry: 'philippines',
    rating: 1,
    category: 'Cup Noodles',
  },
  {
    brand: 'Vifon',
    spicinessLevel: 1,
    originCountry: 'singapore',
    rating: 7,
    category: 'Cup Noodles',
  },
  {
    brand: 'Samyang',
    spicinessLevel: 5,
    originCountry: 'malaysia',
    rating: 2,
    category: 'Packet Noodles',
  },
  {
    brand: 'MyKuali',
    spicinessLevel: 1,
    originCountry: 'vietnam',
    rating: 9,
    category: 'Cup Noodles',
  },
  {
    brand: 'Acecook',
    spicinessLevel: 5,
    originCountry: 'china',
    rating: 1,
    category: 'Packet Noodles',
  },
  {
    brand: 'MyKuali',
    spicinessLevel: 4,
    originCountry: 'taiwan',
    rating: 2,
    category: 'Cup Noodles',
  },
  {
    brand: 'Indomie',
    spicinessLevel: 4,
    originCountry: 'south_korea',
    rating: 10,
    category: 'Cup Noodles',
  },
  {
    brand: 'Paldo',
    spicinessLevel: 5,
    originCountry: 'taiwan',
    rating: 9,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Vifon',
    spicinessLevel: 5,
    originCountry: 'china',
    rating: 3,
    category: 'Cup Noodles',
  },
  {
    brand: 'Vifon',
    spicinessLevel: 5,
    originCountry: 'vietnam',
    rating: 9,
    category: 'Cup Noodles',
  },
  {
    brand: 'TaoKaeNoi',
    spicinessLevel: 2,
    originCountry: 'indonesia',
    rating: 9,
    category: 'Packet Noodles',
  },
  {
    brand: 'Acecook',
    spicinessLevel: 5,
    originCountry: 'philippines',
    rating: 2,
    category: 'Packet Noodles',
  },
  {
    brand: 'Mama',
    spicinessLevel: 3,
    originCountry: 'philippines',
    rating: 1,
    category: 'Bowl Noodles',
  },
  {
    brand: 'MyKuali',
    spicinessLevel: 1,
    originCountry: 'china',
    rating: 6,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Ottogi',
    spicinessLevel: 5,
    originCountry: 'malaysia',
    rating: 5,
    category: 'Bowl Noodles',
  },
  {
    brand: 'MyKuali',
    spicinessLevel: 2,
    originCountry: 'south_korea',
    rating: 7,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Nissin',
    spicinessLevel: 2,
    originCountry: 'japan',
    rating: 2,
    category: 'Bowl Noodles',
  },
  {
    brand: 'TaoKaeNoi',
    spicinessLevel: 1,
    originCountry: 'south_korea',
    rating: 2,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Acecook',
    spicinessLevel: 5,
    originCountry: 'south_korea',
    rating: 10,
    category: 'Packet Noodles',
  },
  {
    brand: 'MyKuali',
    spicinessLevel: 1,
    originCountry: 'singapore',
    rating: 6,
    category: 'Bowl Noodles',
  },
  {
    brand: 'TaoKaeNoi',
    spicinessLevel: 4,
    originCountry: 'thailand',
    rating: 5,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Paldo',
    spicinessLevel: 4,
    originCountry: 'china',
    rating: 2,
    category: 'Cup Noodles',
  },
  {
    brand: 'Nissin',
    spicinessLevel: 3,
    originCountry: 'philippines',
    rating: 8,
    category: 'Packet Noodles',
  },
  {
    brand: 'TaoKaeNoi',
    spicinessLevel: 1,
    originCountry: 'indonesia',
    rating: 2,
    category: 'Cup Noodles',
  },
  {
    brand: 'Nissin',
    spicinessLevel: 2,
    originCountry: 'china',
    rating: 8,
    category: 'Cup Noodles',
  },
  {
    brand: 'Acecook',
    spicinessLevel: 4,
    originCountry: 'indonesia',
    rating: 2,
    category: 'Cup Noodles',
  },
  {
    brand: 'Ottogi',
    spicinessLevel: 3,
    originCountry: 'taiwan',
    rating: 8,
    category: 'Packet Noodles',
  },
  {
    brand: 'MyKuali',
    spicinessLevel: 2,
    originCountry: 'thailand',
    rating: 2,
    category: 'Packet Noodles',
  },
  {
    brand: 'Mama',
    spicinessLevel: 5,
    originCountry: 'taiwan',
    rating: 9,
    category: 'Packet Noodles',
  },
  {
    brand: 'Mama',
    spicinessLevel: 5,
    originCountry: 'south_korea',
    rating: 6,
    category: 'Cup Noodles',
  },
  {
    brand: 'Nissin',
    spicinessLevel: 2,
    originCountry: 'south_korea',
    rating: 3,
    category: 'Cup Noodles',
  },
  {
    brand: 'TaoKaeNoi',
    spicinessLevel: 2,
    originCountry: 'south_korea',
    rating: 6,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Paldo',
    spicinessLevel: 5,
    originCountry: 'taiwan',
    rating: 5,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Ottogi',
    spicinessLevel: 1,
    originCountry: 'malaysia',
    rating: 4,
    category: 'Packet Noodles',
  },
  {
    brand: 'Acecook',
    spicinessLevel: 4,
    originCountry: 'philippines',
    rating: 8,
    category: 'Packet Noodles',
  },
  {
    brand: 'Acecook',
    spicinessLevel: 3,
    originCountry: 'singapore',
    rating: 5,
    category: 'Packet Noodles',
  },
  {
    brand: 'MyKuali',
    spicinessLevel: 1,
    originCountry: 'philippines',
    rating: 7,
    category: 'Cup Noodles',
  },
  {
    brand: 'Mama',
    spicinessLevel: 1,
    originCountry: 'philippines',
    rating: 8,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Ottogi',
    spicinessLevel: 1,
    originCountry: 'indonesia',
    rating: 10,
    category: 'Packet Noodles',
  },
  {
    brand: 'Indomie',
    spicinessLevel: 2,
    originCountry: 'taiwan',
    rating: 1,
    category: 'Packet Noodles',
  },
  {
    brand: 'Samyang',
    spicinessLevel: 3,
    originCountry: 'thailand',
    rating: 10,
    category: 'Cup Noodles',
  },
  {
    brand: 'Mama',
    spicinessLevel: 5,
    originCountry: 'south_korea',
    rating: 6,
    category: 'Cup Noodles',
  },
  {
    brand: 'Vifon',
    spicinessLevel: 1,
    originCountry: 'singapore',
    rating: 3,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Mama',
    spicinessLevel: 5,
    originCountry: 'philippines',
    rating: 8,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Mama',
    spicinessLevel: 2,
    originCountry: 'malaysia',
    rating: 3,
    category: 'Packet Noodles',
  },
  {
    brand: 'Paldo',
    spicinessLevel: 5,
    originCountry: 'malaysia',
    rating: 8,
    category: 'Cup Noodles',
  },
  {
    brand: 'Paldo',
    spicinessLevel: 3,
    originCountry: 'japan',
    rating: 5,
    category: 'Packet Noodles',
  },
  {
    brand: 'Indomie',
    spicinessLevel: 4,
    originCountry: 'japan',
    rating: 10,
    category: 'Cup Noodles',
  },
  {
    brand: 'Nissin',
    spicinessLevel: 1,
    originCountry: 'philippines',
    rating: 2,
    category: 'Packet Noodles',
  },
  {
    brand: 'Vifon',
    spicinessLevel: 1,
    originCountry: 'philippines',
    rating: 10,
    category: 'Packet Noodles',
  },
  {
    brand: 'TaoKaeNoi',
    spicinessLevel: 5,
    originCountry: 'singapore',
    rating: 4,
    category: 'Packet Noodles',
  },
  {
    brand: 'Ottogi',
    spicinessLevel: 5,
    originCountry: 'taiwan',
    rating: 3,
    category: 'Cup Noodles',
  },
  {
    brand: 'Ottogi',
    spicinessLevel: 2,
    originCountry: 'vietnam',
    rating: 2,
    category: 'Packet Noodles',
  },
  {
    brand: 'Vifon',
    spicinessLevel: 4,
    originCountry: 'china',
    rating: 2,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Paldo',
    spicinessLevel: 2,
    originCountry: 'vietnam',
    rating: 5,
    category: 'Cup Noodles',
  },
  {
    brand: 'Acecook',
    spicinessLevel: 4,
    originCountry: 'singapore',
    rating: 5,
    category: 'Cup Noodles',
  },
  {
    brand: 'Samyang',
    spicinessLevel: 1,
    originCountry: 'singapore',
    rating: 10,
    category: 'Packet Noodles',
  },
  {
    brand: 'MyKuali',
    spicinessLevel: 5,
    originCountry: 'south_korea',
    rating: 5,
    category: 'Bowl Noodles',
  },
  {
    brand: 'TaoKaeNoi',
    spicinessLevel: 4,
    originCountry: 'taiwan',
    rating: 4,
    category: 'Packet Noodles',
  },
  {
    brand: 'Acecook',
    spicinessLevel: 5,
    originCountry: 'thailand',
    rating: 2,
    category: 'Cup Noodles',
  },
  {
    brand: 'Samyang',
    spicinessLevel: 5,
    originCountry: 'philippines',
    rating: 3,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Samyang',
    spicinessLevel: 5,
    originCountry: 'south_korea',
    rating: 6,
    category: 'Cup Noodles',
  },
  {
    brand: 'Indomie',
    spicinessLevel: 2,
    originCountry: 'philippines',
    rating: 5,
    category: 'Packet Noodles',
  },
  {
    brand: 'Vifon',
    spicinessLevel: 5,
    originCountry: 'indonesia',
    rating: 6,
    category: 'Packet Noodles',
  },
  {
    brand: 'Paldo',
    spicinessLevel: 3,
    originCountry: 'indonesia',
    rating: 7,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Vifon',
    spicinessLevel: 4,
    originCountry: 'indonesia',
    rating: 7,
    category: 'Cup Noodles',
  },
  {
    brand: 'Mama',
    spicinessLevel: 5,
    originCountry: 'china',
    rating: 7,
    category: 'Packet Noodles',
  },
  {
    brand: 'MyKuali',
    spicinessLevel: 1,
    originCountry: 'china',
    rating: 4,
    category: 'Cup Noodles',
  },
  {
    brand: 'Ottogi',
    spicinessLevel: 5,
    originCountry: 'japan',
    rating: 2,
    category: 'Cup Noodles',
  },
  {
    brand: 'TaoKaeNoi',
    spicinessLevel: 2,
    originCountry: 'japan',
    rating: 5,
    category: 'Packet Noodles',
  },
  {
    brand: 'Nissin',
    spicinessLevel: 2,
    originCountry: 'taiwan',
    rating: 4,
    category: 'Packet Noodles',
  },
  {
    brand: 'Paldo',
    spicinessLevel: 2,
    originCountry: 'malaysia',
    rating: 7,
    category: 'Cup Noodles',
  },
  {
    brand: 'Paldo',
    spicinessLevel: 1,
    originCountry: 'japan',
    rating: 9,
    category: 'Cup Noodles',
  },
  {
    brand: 'Indomie',
    spicinessLevel: 1,
    originCountry: 'thailand',
    rating: 2,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Nissin',
    spicinessLevel: 4,
    originCountry: 'singapore',
    rating: 5,
    category: 'Packet Noodles',
  },
  {
    brand: 'Ottogi',
    spicinessLevel: 3,
    originCountry: 'thailand',
    rating: 2,
    category: 'Packet Noodles',
  },
  {
    brand: 'Ottogi',
    spicinessLevel: 5,
    originCountry: 'indonesia',
    rating: 1,
    category: 'Cup Noodles',
  },
  {
    brand: 'Nissin',
    spicinessLevel: 4,
    originCountry: 'philippines',
    rating: 5,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Samyang',
    spicinessLevel: 2,
    originCountry: 'south_korea',
    rating: 5,
    category: 'Packet Noodles',
  },
  {
    brand: 'Samyang',
    spicinessLevel: 3,
    originCountry: 'indonesia',
    rating: 8,
    category: 'Packet Noodles',
  },
  {
    brand: 'TaoKaeNoi',
    spicinessLevel: 3,
    originCountry: 'indonesia',
    rating: 8,
    category: 'Cup Noodles',
  },
  {
    brand: 'Acecook',
    spicinessLevel: 3,
    originCountry: 'philippines',
    rating: 4,
    category: 'Packet Noodles',
  },
  {
    brand: 'Paldo',
    spicinessLevel: 2,
    originCountry: 'south_korea',
    rating: 6,
    category: 'Cup Noodles',
  },
  {
    brand: 'TaoKaeNoi',
    spicinessLevel: 4,
    originCountry: 'vietnam',
    rating: 7,
    category: 'Cup Noodles',
  },
  {
    brand: 'Mama',
    spicinessLevel: 4,
    originCountry: 'china',
    rating: 6,
    category: 'Packet Noodles',
  },
  {
    brand: 'Indomie',
    spicinessLevel: 5,
    originCountry: 'malaysia',
    rating: 5,
    category: 'Packet Noodles',
  },
  {
    brand: 'Vifon',
    spicinessLevel: 3,
    originCountry: 'vietnam',
    rating: 10,
    category: 'Packet Noodles',
  },
  {
    brand: 'MyKuali',
    spicinessLevel: 3,
    originCountry: 'taiwan',
    rating: 10,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Vifon',
    spicinessLevel: 5,
    originCountry: 'singapore',
    rating: 3,
    category: 'Bowl Noodles',
  },
  {
    brand: 'TaoKaeNoi',
    spicinessLevel: 5,
    originCountry: 'malaysia',
    rating: 7,
    category: 'Cup Noodles',
  },
  {
    brand: 'TaoKaeNoi',
    spicinessLevel: 2,
    originCountry: 'south_korea',
    rating: 3,
    category: 'Cup Noodles',
  },
  {
    brand: 'Ottogi',
    spicinessLevel: 3,
    originCountry: 'indonesia',
    rating: 9,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Acecook',
    spicinessLevel: 1,
    originCountry: 'philippines',
    rating: 9,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Nissin',
    spicinessLevel: 4,
    originCountry: 'south_korea',
    rating: 2,
    category: 'Packet Noodles',
  },
  {
    brand: 'Vifon',
    spicinessLevel: 5,
    originCountry: 'taiwan',
    rating: 2,
    category: 'Bowl Noodles',
  },
  {
    brand: 'TaoKaeNoi',
    spicinessLevel: 2,
    originCountry: 'vietnam',
    rating: 4,
    category: 'Cup Noodles',
  },
  {
    brand: 'Indomie',
    spicinessLevel: 2,
    originCountry: 'singapore',
    rating: 4,
    category: 'Cup Noodles',
  },
  {
    brand: 'TaoKaeNoi',
    spicinessLevel: 2,
    originCountry: 'indonesia',
    rating: 5,
    category: 'Cup Noodles',
  },
  {
    brand: 'Ottogi',
    spicinessLevel: 3,
    originCountry: 'thailand',
    rating: 2,
    category: 'Packet Noodles',
  },
  {
    brand: 'Paldo',
    spicinessLevel: 5,
    originCountry: 'japan',
    rating: 7,
    category: 'Cup Noodles',
  },
  {
    brand: 'Paldo',
    spicinessLevel: 5,
    originCountry: 'japan',
    rating: 3,
    category: 'Cup Noodles',
  },
  {
    brand: 'TaoKaeNoi',
    spicinessLevel: 2,
    originCountry: 'thailand',
    rating: 6,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Indomie',
    spicinessLevel: 1,
    originCountry: 'japan',
    rating: 1,
    category: 'Cup Noodles',
  },
  {
    brand: 'Samyang',
    spicinessLevel: 4,
    originCountry: 'malaysia',
    rating: 4,
    category: 'Cup Noodles',
  },
  {
    brand: 'Acecook',
    spicinessLevel: 2,
    originCountry: 'taiwan',
    rating: 1,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Nissin',
    spicinessLevel: 1,
    originCountry: 'philippines',
    rating: 6,
    category: 'Packet Noodles',
  },
  {
    brand: 'Vifon',
    spicinessLevel: 1,
    originCountry: 'philippines',
    rating: 4,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Ottogi',
    spicinessLevel: 3,
    originCountry: 'japan',
    rating: 7,
    category: 'Cup Noodles',
  },
  {
    brand: 'Nissin',
    spicinessLevel: 1,
    originCountry: 'china',
    rating: 3,
    category: 'Packet Noodles',
  },
  {
    brand: 'Acecook',
    spicinessLevel: 3,
    originCountry: 'thailand',
    rating: 9,
    category: 'Cup Noodles',
  },
  {
    brand: 'Mama',
    spicinessLevel: 1,
    originCountry: 'japan',
    rating: 3,
    category: 'Packet Noodles',
  },
  {
    brand: 'Samyang',
    spicinessLevel: 1,
    originCountry: 'south_korea',
    rating: 5,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Indomie',
    spicinessLevel: 5,
    originCountry: 'singapore',
    rating: 7,
    category: 'Packet Noodles',
  },
  {
    brand: 'Paldo',
    spicinessLevel: 3,
    originCountry: 'south_korea',
    rating: 5,
    category: 'Cup Noodles',
  },
  {
    brand: 'Indomie',
    spicinessLevel: 1,
    originCountry: 'south_korea',
    rating: 6,
    category: 'Packet Noodles',
  },
  {
    brand: 'MyKuali',
    spicinessLevel: 1,
    originCountry: 'japan',
    rating: 2,
    category: 'Cup Noodles',
  },
  {
    brand: 'Paldo',
    spicinessLevel: 2,
    originCountry: 'china',
    rating: 4,
    category: 'Cup Noodles',
  },
  {
    brand: 'Samyang',
    spicinessLevel: 4,
    originCountry: 'indonesia',
    rating: 4,
    category: 'Cup Noodles',
  },
  {
    brand: 'Samyang',
    spicinessLevel: 5,
    originCountry: 'malaysia',
    rating: 4,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Samyang',
    spicinessLevel: 4,
    originCountry: 'singapore',
    rating: 1,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Indomie',
    spicinessLevel: 1,
    originCountry: 'taiwan',
    rating: 5,
    category: 'Packet Noodles',
  },
  {
    brand: 'TaoKaeNoi',
    spicinessLevel: 5,
    originCountry: 'south_korea',
    rating: 7,
    category: 'Cup Noodles',
  },
  {
    brand: 'MyKuali',
    spicinessLevel: 2,
    originCountry: 'malaysia',
    rating: 9,
    category: 'Packet Noodles',
  },
  {
    brand: 'Vifon',
    spicinessLevel: 2,
    originCountry: 'vietnam',
    rating: 7,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Paldo',
    spicinessLevel: 2,
    originCountry: 'thailand',
    rating: 8,
    category: 'Cup Noodles',
  },
  {
    brand: 'Paldo',
    spicinessLevel: 5,
    originCountry: 'japan',
    rating: 5,
    category: 'Cup Noodles',
  },
  {
    brand: 'Samyang',
    spicinessLevel: 2,
    originCountry: 'indonesia',
    rating: 8,
    category: 'Packet Noodles',
  },
  {
    brand: 'MyKuali',
    spicinessLevel: 2,
    originCountry: 'philippines',
    rating: 3,
    category: 'Cup Noodles',
  },
  {
    brand: 'Vifon',
    spicinessLevel: 2,
    originCountry: 'taiwan',
    rating: 5,
    category: 'Packet Noodles',
  },
  {
    brand: 'Samyang',
    spicinessLevel: 3,
    originCountry: 'japan',
    rating: 6,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Nissin',
    spicinessLevel: 4,
    originCountry: 'taiwan',
    rating: 9,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Mama',
    spicinessLevel: 2,
    originCountry: 'taiwan',
    rating: 10,
    category: 'Cup Noodles',
  },
  {
    brand: 'MyKuali',
    spicinessLevel: 3,
    originCountry: 'indonesia',
    rating: 10,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Indomie',
    spicinessLevel: 1,
    originCountry: 'thailand',
    rating: 6,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Indomie',
    spicinessLevel: 5,
    originCountry: 'taiwan',
    rating: 6,
    category: 'Cup Noodles',
  },
  {
    brand: 'Indomie',
    spicinessLevel: 5,
    originCountry: 'vietnam',
    rating: 8,
    category: 'Cup Noodles',
  },
  {
    brand: 'TaoKaeNoi',
    spicinessLevel: 2,
    originCountry: 'singapore',
    rating: 6,
    category: 'Bowl Noodles',
  },
  {
    brand: 'MyKuali',
    spicinessLevel: 1,
    originCountry: 'south_korea',
    rating: 8,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Paldo',
    spicinessLevel: 5,
    originCountry: 'philippines',
    rating: 5,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Mama',
    spicinessLevel: 5,
    originCountry: 'thailand',
    rating: 7,
    category: 'Packet Noodles',
  },
  {
    brand: 'Mama',
    spicinessLevel: 2,
    originCountry: 'vietnam',
    rating: 8,
    category: 'Packet Noodles',
  },
  {
    brand: 'Paldo',
    spicinessLevel: 1,
    originCountry: 'singapore',
    rating: 6,
    category: 'Packet Noodles',
  },
  {
    brand: 'Nissin',
    spicinessLevel: 1,
    originCountry: 'china',
    rating: 4,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Acecook',
    spicinessLevel: 1,
    originCountry: 'singapore',
    rating: 10,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Acecook',
    spicinessLevel: 5,
    originCountry: 'malaysia',
    rating: 3,
    category: 'Packet Noodles',
  },
  {
    brand: 'Mama',
    spicinessLevel: 3,
    originCountry: 'thailand',
    rating: 6,
    category: 'Cup Noodles',
  },
  {
    brand: 'Nissin',
    spicinessLevel: 2,
    originCountry: 'indonesia',
    rating: 6,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Paldo',
    spicinessLevel: 5,
    originCountry: 'china',
    rating: 7,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Ottogi',
    spicinessLevel: 1,
    originCountry: 'japan',
    rating: 9,
    category: 'Cup Noodles',
  },
  {
    brand: 'Vifon',
    spicinessLevel: 2,
    originCountry: 'singapore',
    rating: 5,
    category: 'Cup Noodles',
  },
  {
    brand: 'Nissin',
    spicinessLevel: 3,
    originCountry: 'china',
    rating: 10,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Nissin',
    spicinessLevel: 1,
    originCountry: 'singapore',
    rating: 10,
    category: 'Cup Noodles',
  },
  {
    brand: 'MyKuali',
    spicinessLevel: 1,
    originCountry: 'philippines',
    rating: 2,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Acecook',
    spicinessLevel: 1,
    originCountry: 'singapore',
    rating: 10,
    category: 'Cup Noodles',
  },
  {
    brand: 'TaoKaeNoi',
    spicinessLevel: 1,
    originCountry: 'vietnam',
    rating: 2,
    category: 'Cup Noodles',
  },
  {
    brand: 'Ottogi',
    spicinessLevel: 2,
    originCountry: 'south_korea',
    rating: 4,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Indomie',
    spicinessLevel: 4,
    originCountry: 'philippines',
    rating: 3,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Nissin',
    spicinessLevel: 3,
    originCountry: 'indonesia',
    rating: 7,
    category: 'Packet Noodles',
  },
  {
    brand: 'Nissin',
    spicinessLevel: 2,
    originCountry: 'singapore',
    rating: 10,
    category: 'Packet Noodles',
  },
  {
    brand: 'Vifon',
    spicinessLevel: 4,
    originCountry: 'philippines',
    rating: 4,
    category: 'Packet Noodles',
  },
  {
    brand: 'Mama',
    spicinessLevel: 5,
    originCountry: 'japan',
    rating: 6,
    category: 'Cup Noodles',
  },
  {
    brand: 'Paldo',
    spicinessLevel: 2,
    originCountry: 'indonesia',
    rating: 4,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Ottogi',
    spicinessLevel: 3,
    originCountry: 'vietnam',
    rating: 10,
    category: 'Cup Noodles',
  },
  {
    brand: 'Vifon',
    spicinessLevel: 4,
    originCountry: 'philippines',
    rating: 6,
    category: 'Packet Noodles',
  },
  {
    brand: 'Mama',
    spicinessLevel: 2,
    originCountry: 'malaysia',
    rating: 9,
    category: 'Packet Noodles',
  },
  {
    brand: 'Ottogi',
    spicinessLevel: 3,
    originCountry: 'south_korea',
    rating: 7,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Indomie',
    spicinessLevel: 1,
    originCountry: 'japan',
    rating: 7,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Ottogi',
    spicinessLevel: 1,
    originCountry: 'vietnam',
    rating: 6,
    category: 'Cup Noodles',
  },
  {
    brand: 'Acecook',
    spicinessLevel: 5,
    originCountry: 'singapore',
    rating: 6,
    category: 'Packet Noodles',
  },
  {
    brand: 'Ottogi',
    spicinessLevel: 3,
    originCountry: 'singapore',
    rating: 3,
    category: 'Packet Noodles',
  },
  {
    brand: 'Paldo',
    spicinessLevel: 2,
    originCountry: 'taiwan',
    rating: 1,
    category: 'Cup Noodles',
  },
  {
    brand: 'Indomie',
    spicinessLevel: 1,
    originCountry: 'south_korea',
    rating: 8,
    category: 'Packet Noodles',
  },
  {
    brand: 'TaoKaeNoi',
    spicinessLevel: 5,
    originCountry: 'taiwan',
    rating: 8,
    category: 'Packet Noodles',
  },
  {
    brand: 'MyKuali',
    spicinessLevel: 2,
    originCountry: 'south_korea',
    rating: 3,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Vifon',
    spicinessLevel: 4,
    originCountry: 'singapore',
    rating: 8,
    category: 'Cup Noodles',
  },
  {
    brand: 'Mama',
    spicinessLevel: 1,
    originCountry: 'singapore',
    rating: 7,
    category: 'Packet Noodles',
  },
  {
    brand: 'Ottogi',
    spicinessLevel: 2,
    originCountry: 'thailand',
    rating: 1,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Mama',
    spicinessLevel: 1,
    originCountry: 'indonesia',
    rating: 4,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Paldo',
    spicinessLevel: 3,
    originCountry: 'thailand',
    rating: 2,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Ottogi',
    spicinessLevel: 4,
    originCountry: 'china',
    rating: 8,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Paldo',
    spicinessLevel: 4,
    originCountry: 'indonesia',
    rating: 1,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Ottogi',
    spicinessLevel: 5,
    originCountry: 'indonesia',
    rating: 7,
    category: 'Cup Noodles',
  },
  {
    brand: 'Vifon',
    spicinessLevel: 3,
    originCountry: 'singapore',
    rating: 1,
    category: 'Cup Noodles',
  },
  {
    brand: 'Paldo',
    spicinessLevel: 3,
    originCountry: 'malaysia',
    rating: 8,
    category: 'Cup Noodles',
  },
  {
    brand: 'Indomie',
    spicinessLevel: 1,
    originCountry: 'thailand',
    rating: 4,
    category: 'Packet Noodles',
  },
  {
    brand: 'Nissin',
    spicinessLevel: 3,
    originCountry: 'taiwan',
    rating: 6,
    category: 'Packet Noodles',
  },
  {
    brand: 'Mama',
    spicinessLevel: 2,
    originCountry: 'malaysia',
    rating: 9,
    category: 'Cup Noodles',
  },
  {
    brand: 'Nissin',
    spicinessLevel: 1,
    originCountry: 'south_korea',
    rating: 6,
    category: 'Packet Noodles',
  },
  {
    brand: 'Ottogi',
    spicinessLevel: 2,
    originCountry: 'philippines',
    rating: 5,
    category: 'Cup Noodles',
  },
  {
    brand: 'Samyang',
    spicinessLevel: 4,
    originCountry: 'vietnam',
    rating: 8,
    category: 'Packet Noodles',
  },
  {
    brand: 'Ottogi',
    spicinessLevel: 1,
    originCountry: 'taiwan',
    rating: 6,
    category: 'Packet Noodles',
  },
  {
    brand: 'Mama',
    spicinessLevel: 4,
    originCountry: 'china',
    rating: 7,
    category: 'Cup Noodles',
  },
  {
    brand: 'Acecook',
    spicinessLevel: 5,
    originCountry: 'vietnam',
    rating: 1,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Samyang',
    spicinessLevel: 3,
    originCountry: 'thailand',
    rating: 10,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Indomie',
    spicinessLevel: 1,
    originCountry: 'indonesia',
    rating: 8,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Vifon',
    spicinessLevel: 4,
    originCountry: 'vietnam',
    rating: 3,
    category: 'Cup Noodles',
  },
  {
    brand: 'Paldo',
    spicinessLevel: 5,
    originCountry: 'malaysia',
    rating: 8,
    category: 'Packet Noodles',
  },
  {
    brand: 'Mama',
    spicinessLevel: 2,
    originCountry: 'japan',
    rating: 7,
    category: 'Cup Noodles',
  },
  {
    brand: 'Vifon',
    spicinessLevel: 5,
    originCountry: 'singapore',
    rating: 1,
    category: 'Bowl Noodles',
  },
  {
    brand: 'TaoKaeNoi',
    spicinessLevel: 3,
    originCountry: 'taiwan',
    rating: 10,
    category: 'Packet Noodles',
  },
  {
    brand: 'TaoKaeNoi',
    spicinessLevel: 5,
    originCountry: 'malaysia',
    rating: 9,
    category: 'Cup Noodles',
  },
  {
    brand: 'Samyang',
    spicinessLevel: 4,
    originCountry: 'indonesia',
    rating: 4,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Vifon',
    spicinessLevel: 4,
    originCountry: 'thailand',
    rating: 3,
    category: 'Packet Noodles',
  },
  {
    brand: 'MyKuali',
    spicinessLevel: 5,
    originCountry: 'vietnam',
    rating: 8,
    category: 'Cup Noodles',
  },
  {
    brand: 'Indomie',
    spicinessLevel: 4,
    originCountry: 'taiwan',
    rating: 3,
    category: 'Packet Noodles',
  },
  {
    brand: 'Indomie',
    spicinessLevel: 1,
    originCountry: 'malaysia',
    rating: 7,
    category: 'Cup Noodles',
  },
  {
    brand: 'Ottogi',
    spicinessLevel: 3,
    originCountry: 'thailand',
    rating: 1,
    category: 'Packet Noodles',
  },
  {
    brand: 'Samyang',
    spicinessLevel: 3,
    originCountry: 'china',
    rating: 8,
    category: 'Cup Noodles',
  },
  {
    brand: 'Mama',
    spicinessLevel: 5,
    originCountry: 'malaysia',
    rating: 9,
    category: 'Cup Noodles',
  },
  {
    brand: 'Nissin',
    spicinessLevel: 2,
    originCountry: 'indonesia',
    rating: 9,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Nissin',
    spicinessLevel: 2,
    originCountry: 'singapore',
    rating: 9,
    category: 'Cup Noodles',
  },
  {
    brand: 'Vifon',
    spicinessLevel: 1,
    originCountry: 'taiwan',
    rating: 8,
    category: 'Packet Noodles',
  },
  {
    brand: 'Paldo',
    spicinessLevel: 3,
    originCountry: 'japan',
    rating: 4,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Mama',
    spicinessLevel: 4,
    originCountry: 'philippines',
    rating: 5,
    category: 'Packet Noodles',
  },
  {
    brand: 'Acecook',
    spicinessLevel: 1,
    originCountry: 'china',
    rating: 3,
    category: 'Packet Noodles',
  },
  {
    brand: 'Nissin',
    spicinessLevel: 2,
    originCountry: 'vietnam',
    rating: 7,
    category: 'Packet Noodles',
  },
  {
    brand: 'Mama',
    spicinessLevel: 3,
    originCountry: 'indonesia',
    rating: 4,
    category: 'Packet Noodles',
  },
  {
    brand: 'Indomie',
    spicinessLevel: 3,
    originCountry: 'japan',
    rating: 10,
    category: 'Packet Noodles',
  },
  {
    brand: 'Mama',
    spicinessLevel: 3,
    originCountry: 'indonesia',
    rating: 9,
    category: 'Cup Noodles',
  },
  {
    brand: 'Samyang',
    spicinessLevel: 4,
    originCountry: 'taiwan',
    rating: 1,
    category: 'Bowl Noodles',
  },
  {
    brand: 'TaoKaeNoi',
    spicinessLevel: 1,
    originCountry: 'thailand',
    rating: 1,
    category: 'Cup Noodles',
  },
  {
    brand: 'Acecook',
    spicinessLevel: 4,
    originCountry: 'taiwan',
    rating: 8,
    category: 'Packet Noodles',
  },
  {
    brand: 'Nissin',
    spicinessLevel: 1,
    originCountry: 'japan',
    rating: 7,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Mama',
    spicinessLevel: 4,
    originCountry: 'indonesia',
    rating: 5,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Vifon',
    spicinessLevel: 5,
    originCountry: 'south_korea',
    rating: 10,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Indomie',
    spicinessLevel: 1,
    originCountry: 'vietnam',
    rating: 6,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Nissin',
    spicinessLevel: 3,
    originCountry: 'singapore',
    rating: 6,
    category: 'Packet Noodles',
  },
  {
    brand: 'Mama',
    spicinessLevel: 1,
    originCountry: 'philippines',
    rating: 7,
    category: 'Packet Noodles',
  },
  {
    brand: 'Nissin',
    spicinessLevel: 5,
    originCountry: 'malaysia',
    rating: 8,
    category: 'Cup Noodles',
  },
  {
    brand: 'MyKuali',
    spicinessLevel: 4,
    originCountry: 'japan',
    rating: 8,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Vifon',
    spicinessLevel: 2,
    originCountry: 'singapore',
    rating: 5,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Mama',
    spicinessLevel: 1,
    originCountry: 'vietnam',
    rating: 6,
    category: 'Cup Noodles',
  },
  {
    brand: 'MyKuali',
    spicinessLevel: 3,
    originCountry: 'taiwan',
    rating: 9,
    category: 'Packet Noodles',
  },
  {
    brand: 'TaoKaeNoi',
    spicinessLevel: 5,
    originCountry: 'china',
    rating: 7,
    category: 'Cup Noodles',
  },
  {
    brand: 'Samyang',
    spicinessLevel: 4,
    originCountry: 'philippines',
    rating: 4,
    category: 'Packet Noodles',
  },
  {
    brand: 'Nissin',
    spicinessLevel: 2,
    originCountry: 'vietnam',
    rating: 9,
    category: 'Packet Noodles',
  },
  {
    brand: 'Acecook',
    spicinessLevel: 5,
    originCountry: 'vietnam',
    rating: 5,
    category: 'Packet Noodles',
  },
  {
    brand: 'Mama',
    spicinessLevel: 3,
    originCountry: 'malaysia',
    rating: 9,
    category: 'Packet Noodles',
  },
  {
    brand: 'Vifon',
    spicinessLevel: 1,
    originCountry: 'japan',
    rating: 3,
    category: 'Packet Noodles',
  },
  {
    brand: 'MyKuali',
    spicinessLevel: 4,
    originCountry: 'japan',
    rating: 6,
    category: 'Cup Noodles',
  },
  {
    brand: 'Samyang',
    spicinessLevel: 5,
    originCountry: 'singapore',
    rating: 5,
    category: 'Bowl Noodles',
  },
  {
    brand: 'TaoKaeNoi',
    spicinessLevel: 5,
    originCountry: 'vietnam',
    rating: 7,
    category: 'Cup Noodles',
  },
  {
    brand: 'Samyang',
    spicinessLevel: 3,
    originCountry: 'japan',
    rating: 5,
    category: 'Packet Noodles',
  },
  {
    brand: 'Mama',
    spicinessLevel: 3,
    originCountry: 'singapore',
    rating: 10,
    category: 'Packet Noodles',
  },
  {
    brand: 'Samyang',
    spicinessLevel: 2,
    originCountry: 'vietnam',
    rating: 4,
    category: 'Cup Noodles',
  },
  {
    brand: 'MyKuali',
    spicinessLevel: 2,
    originCountry: 'philippines',
    rating: 2,
    category: 'Cup Noodles',
  },
  {
    brand: 'Samyang',
    spicinessLevel: 5,
    originCountry: 'singapore',
    rating: 3,
    category: 'Packet Noodles',
  },
  {
    brand: 'Indomie',
    spicinessLevel: 1,
    originCountry: 'indonesia',
    rating: 4,
    category: 'Cup Noodles',
  },
  {
    brand: 'Paldo',
    spicinessLevel: 4,
    originCountry: 'vietnam',
    rating: 8,
    category: 'Cup Noodles',
  },
  {
    brand: 'Vifon',
    spicinessLevel: 4,
    originCountry: 'malaysia',
    rating: 1,
    category: 'Packet Noodles',
  },
  {
    brand: 'Vifon',
    spicinessLevel: 3,
    originCountry: 'japan',
    rating: 10,
    category: 'Cup Noodles',
  },
  {
    brand: 'Indomie',
    spicinessLevel: 4,
    originCountry: 'malaysia',
    rating: 7,
    category: 'Cup Noodles',
  },
  {
    brand: 'Nissin',
    spicinessLevel: 4,
    originCountry: 'china',
    rating: 8,
    category: 'Cup Noodles',
  },
  {
    brand: 'Vifon',
    spicinessLevel: 5,
    originCountry: 'south_korea',
    rating: 6,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Nissin',
    spicinessLevel: 1,
    originCountry: 'indonesia',
    rating: 9,
    category: 'Cup Noodles',
  },
  {
    brand: 'Paldo',
    spicinessLevel: 5,
    originCountry: 'vietnam',
    rating: 9,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Acecook',
    spicinessLevel: 4,
    originCountry: 'singapore',
    rating: 9,
    category: 'Packet Noodles',
  },
  {
    brand: 'Paldo',
    spicinessLevel: 2,
    originCountry: 'china',
    rating: 2,
    category: 'Packet Noodles',
  },
  {
    brand: 'Mama',
    spicinessLevel: 3,
    originCountry: 'china',
    rating: 4,
    category: 'Cup Noodles',
  },
  {
    brand: 'Indomie',
    spicinessLevel: 2,
    originCountry: 'south_korea',
    rating: 3,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Mama',
    spicinessLevel: 3,
    originCountry: 'thailand',
    rating: 1,
    category: 'Packet Noodles',
  },
  {
    brand: 'MyKuali',
    spicinessLevel: 2,
    originCountry: 'malaysia',
    rating: 6,
    category: 'Cup Noodles',
  },
  {
    brand: 'Indomie',
    spicinessLevel: 3,
    originCountry: 'thailand',
    rating: 6,
    category: 'Cup Noodles',
  },
  {
    brand: 'TaoKaeNoi',
    spicinessLevel: 3,
    originCountry: 'vietnam',
    rating: 3,
    category: 'Cup Noodles',
  },
  {
    brand: 'Ottogi',
    spicinessLevel: 4,
    originCountry: 'south_korea',
    rating: 1,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Vifon',
    spicinessLevel: 3,
    originCountry: 'singapore',
    rating: 6,
    category: 'Packet Noodles',
  },
  {
    brand: 'Indomie',
    spicinessLevel: 4,
    originCountry: 'malaysia',
    rating: 7,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Indomie',
    spicinessLevel: 4,
    originCountry: 'china',
    rating: 2,
    category: 'Packet Noodles',
  },
  {
    brand: 'Indomie',
    spicinessLevel: 3,
    originCountry: 'singapore',
    rating: 4,
    category: 'Cup Noodles',
  },
  {
    brand: 'Ottogi',
    spicinessLevel: 4,
    originCountry: 'japan',
    rating: 5,
    category: 'Packet Noodles',
  },
  {
    brand: 'Acecook',
    spicinessLevel: 3,
    originCountry: 'indonesia',
    rating: 3,
    category: 'Bowl Noodles',
  },
  {
    brand: 'TaoKaeNoi',
    spicinessLevel: 5,
    originCountry: 'japan',
    rating: 9,
    category: 'Packet Noodles',
  },
  {
    brand: 'TaoKaeNoi',
    spicinessLevel: 5,
    originCountry: 'taiwan',
    rating: 2,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Ottogi',
    spicinessLevel: 4,
    originCountry: 'china',
    rating: 9,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Vifon',
    spicinessLevel: 5,
    originCountry: 'vietnam',
    rating: 8,
    category: 'Packet Noodles',
  },
  {
    brand: 'Mama',
    spicinessLevel: 2,
    originCountry: 'vietnam',
    rating: 6,
    category: 'Packet Noodles',
  },
  {
    brand: 'Nissin',
    spicinessLevel: 4,
    originCountry: 'thailand',
    rating: 6,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Acecook',
    spicinessLevel: 4,
    originCountry: 'japan',
    rating: 10,
    category: 'Packet Noodles',
  },
  {
    brand: 'Ottogi',
    spicinessLevel: 2,
    originCountry: 'thailand',
    rating: 10,
    category: 'Cup Noodles',
  },
  {
    brand: 'TaoKaeNoi',
    spicinessLevel: 1,
    originCountry: 'taiwan',
    rating: 2,
    category: 'Packet Noodles',
  },
  {
    brand: 'Ottogi',
    spicinessLevel: 1,
    originCountry: 'south_korea',
    rating: 1,
    category: 'Packet Noodles',
  },
  {
    brand: 'TaoKaeNoi',
    spicinessLevel: 2,
    originCountry: 'south_korea',
    rating: 2,
    category: 'Packet Noodles',
  },
  {
    brand: 'Vifon',
    spicinessLevel: 2,
    originCountry: 'south_korea',
    rating: 7,
    category: 'Cup Noodles',
  },
  {
    brand: 'Samyang',
    spicinessLevel: 3,
    originCountry: 'thailand',
    rating: 7,
    category: 'Packet Noodles',
  },
  {
    brand: 'Samyang',
    spicinessLevel: 2,
    originCountry: 'taiwan',
    rating: 4,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Ottogi',
    spicinessLevel: 5,
    originCountry: 'thailand',
    rating: 8,
    category: 'Packet Noodles',
  },
  {
    brand: 'Ottogi',
    spicinessLevel: 4,
    originCountry: 'china',
    rating: 6,
    category: 'Cup Noodles',
  },
  {
    brand: 'MyKuali',
    spicinessLevel: 3,
    originCountry: 'malaysia',
    rating: 2,
    category: 'Packet Noodles',
  },
  {
    brand: 'MyKuali',
    spicinessLevel: 3,
    originCountry: 'thailand',
    rating: 1,
    category: 'Packet Noodles',
  },
  {
    brand: 'Samyang',
    spicinessLevel: 1,
    originCountry: 'indonesia',
    rating: 7,
    category: 'Cup Noodles',
  },
  {
    brand: 'Nissin',
    spicinessLevel: 1,
    originCountry: 'singapore',
    rating: 3,
    category: 'Cup Noodles',
  },
  {
    brand: 'Mama',
    spicinessLevel: 2,
    originCountry: 'china',
    rating: 5,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Samyang',
    spicinessLevel: 2,
    originCountry: 'taiwan',
    rating: 4,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Acecook',
    spicinessLevel: 1,
    originCountry: 'indonesia',
    rating: 1,
    category: 'Packet Noodles',
  },
  {
    brand: 'Samyang',
    spicinessLevel: 2,
    originCountry: 'vietnam',
    rating: 10,
    category: 'Packet Noodles',
  },
  {
    brand: 'MyKuali',
    spicinessLevel: 1,
    originCountry: 'malaysia',
    rating: 5,
    category: 'Cup Noodles',
  },
  {
    brand: 'Acecook',
    spicinessLevel: 4,
    originCountry: 'thailand',
    rating: 5,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Samyang',
    spicinessLevel: 1,
    originCountry: 'indonesia',
    rating: 4,
    category: 'Cup Noodles',
  },
  {
    brand: 'Nissin',
    spicinessLevel: 4,
    originCountry: 'vietnam',
    rating: 3,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Mama',
    spicinessLevel: 5,
    originCountry: 'philippines',
    rating: 8,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Vifon',
    spicinessLevel: 1,
    originCountry: 'philippines',
    rating: 7,
    category: 'Packet Noodles',
  },
  {
    brand: 'TaoKaeNoi',
    spicinessLevel: 1,
    originCountry: 'thailand',
    rating: 10,
    category: 'Packet Noodles',
  },
  {
    brand: 'Mama',
    spicinessLevel: 3,
    originCountry: 'south_korea',
    rating: 8,
    category: 'Cup Noodles',
  },
  {
    brand: 'TaoKaeNoi',
    spicinessLevel: 2,
    originCountry: 'taiwan',
    rating: 10,
    category: 'Cup Noodles',
  },
  {
    brand: 'Vifon',
    spicinessLevel: 4,
    originCountry: 'singapore',
    rating: 9,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Samyang',
    spicinessLevel: 4,
    originCountry: 'malaysia',
    rating: 10,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Acecook',
    spicinessLevel: 5,
    originCountry: 'singapore',
    rating: 10,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Acecook',
    spicinessLevel: 2,
    originCountry: 'philippines',
    rating: 3,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Nissin',
    spicinessLevel: 2,
    originCountry: 'vietnam',
    rating: 3,
    category: 'Packet Noodles',
  },
  {
    brand: 'Acecook',
    spicinessLevel: 4,
    originCountry: 'japan',
    rating: 8,
    category: 'Packet Noodles',
  },
  {
    brand: 'Ottogi',
    spicinessLevel: 1,
    originCountry: 'indonesia',
    rating: 1,
    category: 'Packet Noodles',
  },
  {
    brand: 'Nissin',
    spicinessLevel: 5,
    originCountry: 'thailand',
    rating: 7,
    category: 'Cup Noodles',
  },
  {
    brand: 'Ottogi',
    spicinessLevel: 3,
    originCountry: 'japan',
    rating: 8,
    category: 'Packet Noodles',
  },
  {
    brand: 'MyKuali',
    spicinessLevel: 1,
    originCountry: 'philippines',
    rating: 1,
    category: 'Packet Noodles',
  },
  {
    brand: 'Paldo',
    spicinessLevel: 4,
    originCountry: 'china',
    rating: 1,
    category: 'Cup Noodles',
  },
  {
    brand: 'Mama',
    spicinessLevel: 1,
    originCountry: 'vietnam',
    rating: 6,
    category: 'Cup Noodles',
  },
  {
    brand: 'Samyang',
    spicinessLevel: 3,
    originCountry: 'indonesia',
    rating: 9,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Vifon',
    spicinessLevel: 1,
    originCountry: 'china',
    rating: 9,
    category: 'Cup Noodles',
  },
  {
    brand: 'Samyang',
    spicinessLevel: 4,
    originCountry: 'south_korea',
    rating: 10,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Indomie',
    spicinessLevel: 2,
    originCountry: 'vietnam',
    rating: 7,
    category: 'Cup Noodles',
  },
  {
    brand: 'Samyang',
    spicinessLevel: 3,
    originCountry: 'taiwan',
    rating: 4,
    category: 'Cup Noodles',
  },
  {
    brand: 'Acecook',
    spicinessLevel: 4,
    originCountry: 'malaysia',
    rating: 2,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Paldo',
    spicinessLevel: 2,
    originCountry: 'malaysia',
    rating: 7,
    category: 'Cup Noodles',
  },
  {
    brand: 'Ottogi',
    spicinessLevel: 1,
    originCountry: 'china',
    rating: 3,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Mama',
    spicinessLevel: 1,
    originCountry: 'indonesia',
    rating: 9,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Acecook',
    spicinessLevel: 1,
    originCountry: 'indonesia',
    rating: 1,
    category: 'Cup Noodles',
  },
  {
    brand: 'Paldo',
    spicinessLevel: 5,
    originCountry: 'taiwan',
    rating: 3,
    category: 'Cup Noodles',
  },
  {
    brand: 'Mama',
    spicinessLevel: 5,
    originCountry: 'philippines',
    rating: 1,
    category: 'Cup Noodles',
  },
  {
    brand: 'Samyang',
    spicinessLevel: 2,
    originCountry: 'indonesia',
    rating: 2,
    category: 'Packet Noodles',
  },
  {
    brand: 'Paldo',
    spicinessLevel: 3,
    originCountry: 'singapore',
    rating: 7,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Paldo',
    spicinessLevel: 1,
    originCountry: 'malaysia',
    rating: 6,
    category: 'Packet Noodles',
  },
  {
    brand: 'Ottogi',
    spicinessLevel: 3,
    originCountry: 'vietnam',
    rating: 9,
    category: 'Cup Noodles',
  },
  {
    brand: 'Nissin',
    spicinessLevel: 5,
    originCountry: 'china',
    rating: 1,
    category: 'Packet Noodles',
  },
  {
    brand: 'Acecook',
    spicinessLevel: 2,
    originCountry: 'south_korea',
    rating: 3,
    category: 'Packet Noodles',
  },
  {
    brand: 'Paldo',
    spicinessLevel: 1,
    originCountry: 'philippines',
    rating: 8,
    category: 'Cup Noodles',
  },
  {
    brand: 'Vifon',
    spicinessLevel: 1,
    originCountry: 'china',
    rating: 5,
    category: 'Packet Noodles',
  },
  {
    brand: 'TaoKaeNoi',
    spicinessLevel: 1,
    originCountry: 'vietnam',
    rating: 3,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Samyang',
    spicinessLevel: 4,
    originCountry: 'singapore',
    rating: 10,
    category: 'Cup Noodles',
  },
  {
    brand: 'Vifon',
    spicinessLevel: 2,
    originCountry: 'china',
    rating: 6,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Vifon',
    spicinessLevel: 4,
    originCountry: 'china',
    rating: 10,
    category: 'Packet Noodles',
  },
  {
    brand: 'Mama',
    spicinessLevel: 5,
    originCountry: 'vietnam',
    rating: 9,
    category: 'Bowl Noodles',
  },
  {
    brand: 'MyKuali',
    spicinessLevel: 4,
    originCountry: 'vietnam',
    rating: 3,
    category: 'Packet Noodles',
  },
  {
    brand: 'TaoKaeNoi',
    spicinessLevel: 5,
    originCountry: 'philippines',
    rating: 3,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Vifon',
    spicinessLevel: 1,
    originCountry: 'south_korea',
    rating: 5,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Samyang',
    spicinessLevel: 5,
    originCountry: 'vietnam',
    rating: 9,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Acecook',
    spicinessLevel: 3,
    originCountry: 'malaysia',
    rating: 5,
    category: 'Cup Noodles',
  },
  {
    brand: 'Mama',
    spicinessLevel: 2,
    originCountry: 'south_korea',
    rating: 5,
    category: 'Packet Noodles',
  },
  {
    brand: 'MyKuali',
    spicinessLevel: 5,
    originCountry: 'taiwan',
    rating: 4,
    category: 'Cup Noodles',
  },
  {
    brand: 'Acecook',
    spicinessLevel: 4,
    originCountry: 'philippines',
    rating: 4,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Vifon',
    spicinessLevel: 3,
    originCountry: 'philippines',
    rating: 5,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Mama',
    spicinessLevel: 4,
    originCountry: 'china',
    rating: 8,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Acecook',
    spicinessLevel: 2,
    originCountry: 'vietnam',
    rating: 5,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Nissin',
    spicinessLevel: 3,
    originCountry: 'singapore',
    rating: 4,
    category: 'Cup Noodles',
  },
  {
    brand: 'MyKuali',
    spicinessLevel: 1,
    originCountry: 'indonesia',
    rating: 3,
    category: 'Cup Noodles',
  },
  {
    brand: 'Nissin',
    spicinessLevel: 2,
    originCountry: 'taiwan',
    rating: 8,
    category: 'Cup Noodles',
  },
  {
    brand: 'Acecook',
    spicinessLevel: 4,
    originCountry: 'philippines',
    rating: 2,
    category: 'Packet Noodles',
  },
  {
    brand: 'MyKuali',
    spicinessLevel: 4,
    originCountry: 'thailand',
    rating: 3,
    category: 'Bowl Noodles',
  },
  {
    brand: 'TaoKaeNoi',
    spicinessLevel: 1,
    originCountry: 'thailand',
    rating: 2,
    category: 'Cup Noodles',
  },
  {
    brand: 'Ottogi',
    spicinessLevel: 2,
    originCountry: 'singapore',
    rating: 10,
    category: 'Cup Noodles',
  },
  {
    brand: 'TaoKaeNoi',
    spicinessLevel: 1,
    originCountry: 'china',
    rating: 1,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Acecook',
    spicinessLevel: 5,
    originCountry: 'china',
    rating: 4,
    category: 'Packet Noodles',
  },
  {
    brand: 'Nissin',
    spicinessLevel: 5,
    originCountry: 'malaysia',
    rating: 2,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Mama',
    spicinessLevel: 5,
    originCountry: 'indonesia',
    rating: 8,
    category: 'Packet Noodles',
  },
  {
    brand: 'Acecook',
    spicinessLevel: 4,
    originCountry: 'thailand',
    rating: 3,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Mama',
    spicinessLevel: 2,
    originCountry: 'singapore',
    rating: 1,
    category: 'Packet Noodles',
  },
  {
    brand: 'Acecook',
    spicinessLevel: 2,
    originCountry: 'indonesia',
    rating: 8,
    category: 'Cup Noodles',
  },
  {
    brand: 'Paldo',
    spicinessLevel: 1,
    originCountry: 'thailand',
    rating: 1,
    category: 'Cup Noodles',
  },
  {
    brand: 'Paldo',
    spicinessLevel: 1,
    originCountry: 'malaysia',
    rating: 5,
    category: 'Cup Noodles',
  },
  {
    brand: 'Vifon',
    spicinessLevel: 4,
    originCountry: 'thailand',
    rating: 4,
    category: 'Cup Noodles',
  },
  {
    brand: 'Ottogi',
    spicinessLevel: 3,
    originCountry: 'south_korea',
    rating: 5,
    category: 'Cup Noodles',
  },
  {
    brand: 'MyKuali',
    spicinessLevel: 3,
    originCountry: 'malaysia',
    rating: 6,
    category: 'Cup Noodles',
  },
  {
    brand: 'Indomie',
    spicinessLevel: 2,
    originCountry: 'indonesia',
    rating: 10,
    category: 'Cup Noodles',
  },
  {
    brand: 'TaoKaeNoi',
    spicinessLevel: 5,
    originCountry: 'china',
    rating: 1,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Acecook',
    spicinessLevel: 1,
    originCountry: 'china',
    rating: 4,
    category: 'Packet Noodles',
  },
  {
    brand: 'MyKuali',
    spicinessLevel: 3,
    originCountry: 'philippines',
    rating: 3,
    category: 'Cup Noodles',
  },
  {
    brand: 'Indomie',
    spicinessLevel: 3,
    originCountry: 'philippines',
    rating: 8,
    category: 'Packet Noodles',
  },
  {
    brand: 'Samyang',
    spicinessLevel: 2,
    originCountry: 'china',
    rating: 9,
    category: 'Cup Noodles',
  },
  {
    brand: 'Vifon',
    spicinessLevel: 3,
    originCountry: 'japan',
    rating: 8,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Indomie',
    spicinessLevel: 4,
    originCountry: 'thailand',
    rating: 4,
    category: 'Cup Noodles',
  },
  {
    brand: 'Indomie',
    spicinessLevel: 1,
    originCountry: 'vietnam',
    rating: 8,
    category: 'Packet Noodles',
  },
  {
    brand: 'Vifon',
    spicinessLevel: 5,
    originCountry: 'china',
    rating: 8,
    category: 'Cup Noodles',
  },
  {
    brand: 'TaoKaeNoi',
    spicinessLevel: 5,
    originCountry: 'japan',
    rating: 8,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Nissin',
    spicinessLevel: 5,
    originCountry: 'indonesia',
    rating: 3,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Nissin',
    spicinessLevel: 1,
    originCountry: 'singapore',
    rating: 1,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Ottogi',
    spicinessLevel: 2,
    originCountry: 'philippines',
    rating: 3,
    category: 'Cup Noodles',
  },
  {
    brand: 'Nissin',
    spicinessLevel: 4,
    originCountry: 'thailand',
    rating: 3,
    category: 'Bowl Noodles',
  },
  {
    brand: 'TaoKaeNoi',
    spicinessLevel: 4,
    originCountry: 'thailand',
    rating: 4,
    category: 'Cup Noodles',
  },
  {
    brand: 'Paldo',
    spicinessLevel: 2,
    originCountry: 'thailand',
    rating: 10,
    category: 'Packet Noodles',
  },
  {
    brand: 'Paldo',
    spicinessLevel: 4,
    originCountry: 'china',
    rating: 5,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Mama',
    spicinessLevel: 4,
    originCountry: 'taiwan',
    rating: 5,
    category: 'Packet Noodles',
  },
  {
    brand: 'Indomie',
    spicinessLevel: 3,
    originCountry: 'taiwan',
    rating: 4,
    category: 'Packet Noodles',
  },
  {
    brand: 'Vifon',
    spicinessLevel: 4,
    originCountry: 'thailand',
    rating: 7,
    category: 'Cup Noodles',
  },
  {
    brand: 'Paldo',
    spicinessLevel: 1,
    originCountry: 'philippines',
    rating: 8,
    category: 'Packet Noodles',
  },
  {
    brand: 'TaoKaeNoi',
    spicinessLevel: 1,
    originCountry: 'taiwan',
    rating: 1,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Ottogi',
    spicinessLevel: 1,
    originCountry: 'singapore',
    rating: 10,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Indomie',
    spicinessLevel: 3,
    originCountry: 'china',
    rating: 5,
    category: 'Cup Noodles',
  },
  {
    brand: 'Mama',
    spicinessLevel: 4,
    originCountry: 'singapore',
    rating: 8,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Ottogi',
    spicinessLevel: 4,
    originCountry: 'indonesia',
    rating: 5,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Vifon',
    spicinessLevel: 2,
    originCountry: 'malaysia',
    rating: 2,
    category: 'Cup Noodles',
  },
  {
    brand: 'Vifon',
    spicinessLevel: 5,
    originCountry: 'thailand',
    rating: 3,
    category: 'Packet Noodles',
  },
  {
    brand: 'Paldo',
    spicinessLevel: 2,
    originCountry: 'taiwan',
    rating: 7,
    category: 'Packet Noodles',
  },
  {
    brand: 'Acecook',
    spicinessLevel: 5,
    originCountry: 'taiwan',
    rating: 10,
    category: 'Packet Noodles',
  },
  {
    brand: 'Acecook',
    spicinessLevel: 5,
    originCountry: 'thailand',
    rating: 2,
    category: 'Cup Noodles',
  },
  {
    brand: 'Nissin',
    spicinessLevel: 5,
    originCountry: 'south_korea',
    rating: 5,
    category: 'Packet Noodles',
  },
  {
    brand: 'TaoKaeNoi',
    spicinessLevel: 3,
    originCountry: 'china',
    rating: 5,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Vifon',
    spicinessLevel: 1,
    originCountry: 'south_korea',
    rating: 1,
    category: 'Cup Noodles',
  },
  {
    brand: 'Samyang',
    spicinessLevel: 1,
    originCountry: 'china',
    rating: 3,
    category: 'Packet Noodles',
  },
  {
    brand: 'Paldo',
    spicinessLevel: 3,
    originCountry: 'vietnam',
    rating: 3,
    category: 'Cup Noodles',
  },
  {
    brand: 'Mama',
    spicinessLevel: 1,
    originCountry: 'taiwan',
    rating: 8,
    category: 'Packet Noodles',
  },
  {
    brand: 'Ottogi',
    spicinessLevel: 5,
    originCountry: 'china',
    rating: 1,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Mama',
    spicinessLevel: 2,
    originCountry: 'indonesia',
    rating: 2,
    category: 'Cup Noodles',
  },
  {
    brand: 'Mama',
    spicinessLevel: 2,
    originCountry: 'singapore',
    rating: 7,
    category: 'Bowl Noodles',
  },
  {
    brand: 'TaoKaeNoi',
    spicinessLevel: 1,
    originCountry: 'philippines',
    rating: 8,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Vifon',
    spicinessLevel: 2,
    originCountry: 'japan',
    rating: 1,
    category: 'Bowl Noodles',
  },
  {
    brand: 'Ottogi',
    spicinessLevel: 3,
    originCountry: 'japan',
    rating: 7,
    category: 'Packet Noodles',
  },
  {
    brand: 'Samyang',
    spicinessLevel: 3,
    originCountry: 'philippines',
    rating: 4,
    category: 'Cup Noodles',
  },
  {
    brand: 'TaoKaeNoi',
    spicinessLevel: 5,
    originCountry: 'taiwan',
    rating: 2,
    category: 'Cup Noodles',
  },
  {
    brand: 'TaoKaeNoi',
    spicinessLevel: 3,
    originCountry: 'philippines',
    rating: 7,
    category: 'Bowl Noodles',
  },
];

export default instantNoodles;
