const noodles = [
  {
    name: 'Indomie Rice Noodles #1',
    brand: 'Indomie',
    spicinessLevel: 2,
    originCountry: 'south_korea',
    rating: 10,
    category: 'Rice Noodles',
  },
  {
    name: 'Wai Wai Ramen #2',
    brand: 'Wai Wai',
    spicinessLevel: 2,
    originCountry: 'philippines',
    rating: 9,
    category: 'Ramen',
  },
  {
    name: 'Maggi Tom Yum #3',
    brand: 'Maggi',
    spicinessLevel: 4,
    originCountry: 'indonesia',
    rating: 8,
    category: 'Tom Yum',
  },
  {
    name: 'Indomie Curry Noodles #4',
    brand: 'Indomie',
    spicinessLevel: 1,
    originCountry: 'china',
    rating: 9,
    category: 'Curry Noodles',
  },
  {
    name: 'Vifon Ramen #5',
    brand: 'Vifon',
    spicinessLevel: 1,
    originCountry: 'japan',
    rating: 9,
    category: 'Ramen',
  },
  {
    name: 'Knorr Ramen #6',
    brand: 'Knorr',
    spicinessLevel: 3,
    originCountry: 'thailand',
    rating: 10,
    category: 'Ramen',
  },
  {
    name: 'Acecook Tom Yum #7',
    brand: 'Acecook',
    spicinessLevel: 4,
    originCountry: 'singapore',
    rating: 7,
    category: 'Tom Yum',
  },
  {
    name: 'Vifon Tom Yum #8',
    brand: 'Vifon',
    spicinessLevel: 5,
    originCountry: 'philippines',
    rating: 5,
    category: 'Tom Yum',
  },
  {
    name: 'Mama Fried Noodles #9',
    brand: 'Mama',
    spicinessLevel: 5,
    originCountry: 'south_korea',
    rating: 5,
    category: 'Fried Noodles',
  },
  {
    name: 'Maruchan Instant Udon #10',
    brand: 'Maruchan',
    spicinessLevel: 5,
    originCountry: 'vietnam',
    rating: 8,
    category: 'Instant Udon',
  },
  {
    name: 'Koka Tom Yum #11',
    brand: 'Koka',
    spicinessLevel: 1,
    originCountry: 'singapore',
    rating: 5,
    category: 'Tom Yum',
  },
  {
    name: 'Acecook Ramen #12',
    brand: 'Acecook',
    spicinessLevel: 3,
    originCountry: 'vietnam',
    rating: 8,
    category: 'Ramen',
  },
  {
    name: 'Tao Kae Noi Laksa #13',
    brand: 'Tao Kae Noi',
    spicinessLevel: 3,
    originCountry: 'china',
    rating: 9,
    category: 'Laksa',
  },
  {
    name: 'Paldo Instant Udon #14',
    brand: 'Paldo',
    spicinessLevel: 5,
    originCountry: 'china',
    rating: 5,
    category: 'Instant Udon',
  },
  {
    name: 'Mama Laksa #15',
    brand: 'Mama',
    spicinessLevel: 1,
    originCountry: 'indonesia',
    rating: 9,
    category: 'Laksa',
  },
  {
    name: 'Nissin Instant Udon #16',
    brand: 'Nissin',
    spicinessLevel: 2,
    originCountry: 'indonesia',
    rating: 10,
    category: 'Instant Udon',
  },
  {
    name: 'Nongshim Soba #17',
    brand: 'Nongshim',
    spicinessLevel: 3,
    originCountry: 'thailand',
    rating: 10,
    category: 'Soba',
  },
  {
    name: 'Tao Kae Noi Soba #18',
    brand: 'Tao Kae Noi',
    spicinessLevel: 2,
    originCountry: 'malaysia',
    rating: 6,
    category: 'Soba',
  },
  {
    name: 'Nissin Rice Noodles #19',
    brand: 'Nissin',
    spicinessLevel: 4,
    originCountry: 'vietnam',
    rating: 5,
    category: 'Rice Noodles',
  },
  {
    name: 'Maggi Laksa #20',
    brand: 'Maggi',
    spicinessLevel: 2,
    originCountry: 'taiwan',
    rating: 9,
    category: 'Laksa',
  },
  {
    name: 'Samyang Ramen #21',
    brand: 'Samyang',
    spicinessLevel: 2,
    originCountry: 'malaysia',
    rating: 6,
    category: 'Ramen',
  },
  {
    name: 'Mama Tom Yum #22',
    brand: 'Mama',
    spicinessLevel: 3,
    originCountry: 'vietnam',
    rating: 7,
    category: 'Tom Yum',
  },
  {
    name: 'Paldo Tom Yum #23',
    brand: 'Paldo',
    spicinessLevel: 1,
    originCountry: 'thailand',
    rating: 10,
    category: 'Tom Yum',
  },
  {
    name: 'Indomie Cup Noodles #24',
    brand: 'Indomie',
    spicinessLevel: 5,
    originCountry: 'thailand',
    rating: 6,
    category: 'Cup Noodles',
  },
  {
    name: 'Wai Wai Ramen #25',
    brand: 'Wai Wai',
    spicinessLevel: 2,
    originCountry: 'singapore',
    rating: 8,
    category: 'Ramen',
  },
  {
    name: 'Wei Lih Rice Noodles #26',
    brand: 'Wei Lih',
    spicinessLevel: 1,
    originCountry: 'thailand',
    rating: 10,
    category: 'Rice Noodles',
  },
  {
    name: 'Koka Rice Noodles #27',
    brand: 'Koka',
    spicinessLevel: 1,
    originCountry: 'taiwan',
    rating: 9,
    category: 'Rice Noodles',
  },
  {
    name: 'Maggi Fried Noodles #28',
    brand: 'Maggi',
    spicinessLevel: 1,
    originCountry: 'thailand',
    rating: 9,
    category: 'Fried Noodles',
  },
  {
    name: 'Wai Wai Curry Noodles #29',
    brand: 'Wai Wai',
    spicinessLevel: 1,
    originCountry: 'vietnam',
    rating: 10,
    category: 'Curry Noodles',
  },
  {
    name: 'Maruchan Ramen #30',
    brand: 'Maruchan',
    spicinessLevel: 5,
    originCountry: 'vietnam',
    rating: 9,
    category: 'Ramen',
  },
  {
    name: 'Maggi Fried Noodles #31',
    brand: 'Maggi',
    spicinessLevel: 5,
    originCountry: 'china',
    rating: 9,
    category: 'Fried Noodles',
  },
  {
    name: 'Mama Rice Noodles #32',
    brand: 'Mama',
    spicinessLevel: 5,
    originCountry: 'indonesia',
    rating: 5,
    category: 'Rice Noodles',
  },
  {
    name: 'Acecook Soba #33',
    brand: 'Acecook',
    spicinessLevel: 1,
    originCountry: 'singapore',
    rating: 6,
    category: 'Soba',
  },
  {
    name: 'Koka Soba #34',
    brand: 'Koka',
    spicinessLevel: 3,
    originCountry: 'taiwan',
    rating: 9,
    category: 'Soba',
  },
  {
    name: 'Nissin Curry Noodles #35',
    brand: 'Nissin',
    spicinessLevel: 3,
    originCountry: 'china',
    rating: 7,
    category: 'Curry Noodles',
  },
  {
    name: 'Tao Kae Noi Soba #36',
    brand: 'Tao Kae Noi',
    spicinessLevel: 3,
    originCountry: 'malaysia',
    rating: 5,
    category: 'Soba',
  },
  {
    name: 'Paldo Spicy Ramen #37',
    brand: 'Paldo',
    spicinessLevel: 5,
    originCountry: 'indonesia',
    rating: 7,
    category: 'Spicy Ramen',
  },
  {
    name: 'Samyang Cup Noodles #38',
    brand: 'Samyang',
    spicinessLevel: 5,
    originCountry: 'thailand',
    rating: 7,
    category: 'Cup Noodles',
  },
  {
    name: 'Indomie Tom Yum #39',
    brand: 'Indomie',
    spicinessLevel: 2,
    originCountry: 'indonesia',
    rating: 9,
    category: 'Tom Yum',
  },
  {
    name: "Ching's Secret Tom Yum #40",
    brand: "Ching's Secret",
    spicinessLevel: 3,
    originCountry: 'philippines',
    rating: 10,
    category: 'Tom Yum',
  },
  {
    name: 'MyKuali Ramen #41',
    brand: 'MyKuali',
    spicinessLevel: 1,
    originCountry: 'thailand',
    rating: 5,
    category: 'Ramen',
  },
  {
    name: 'Nissin Soba #42',
    brand: 'Nissin',
    spicinessLevel: 3,
    originCountry: 'china',
    rating: 6,
    category: 'Soba',
  },
  {
    name: 'Indomie Instant Udon #43',
    brand: 'Indomie',
    spicinessLevel: 2,
    originCountry: 'singapore',
    rating: 6,
    category: 'Instant Udon',
  },
  {
    name: 'Ottogi Rice Noodles #44',
    brand: 'Ottogi',
    spicinessLevel: 2,
    originCountry: 'indonesia',
    rating: 7,
    category: 'Rice Noodles',
  },
  {
    name: 'Nissin Laksa #45',
    brand: 'Nissin',
    spicinessLevel: 1,
    originCountry: 'singapore',
    rating: 6,
    category: 'Laksa',
  },
  {
    name: 'Ottogi Fried Noodles #46',
    brand: 'Ottogi',
    spicinessLevel: 4,
    originCountry: 'south_korea',
    rating: 6,
    category: 'Fried Noodles',
  },
  {
    name: 'Nongshim Curry Noodles #47',
    brand: 'Nongshim',
    spicinessLevel: 4,
    originCountry: 'china',
    rating: 6,
    category: 'Curry Noodles',
  },
  {
    name: 'Samyang Instant Udon #48',
    brand: 'Samyang',
    spicinessLevel: 2,
    originCountry: 'taiwan',
    rating: 5,
    category: 'Instant Udon',
  },
  {
    name: 'Nissin Soba #49',
    brand: 'Nissin',
    spicinessLevel: 1,
    originCountry: 'vietnam',
    rating: 6,
    category: 'Soba',
  },
  {
    name: 'Maggi Laksa #50',
    brand: 'Maggi',
    spicinessLevel: 4,
    originCountry: 'vietnam',
    rating: 6,
    category: 'Laksa',
  },
  {
    name: 'Vifon Instant Udon #51',
    brand: 'Vifon',
    spicinessLevel: 4,
    originCountry: 'china',
    rating: 6,
    category: 'Instant Udon',
  },
  {
    name: 'Wei Lih Laksa #52',
    brand: 'Wei Lih',
    spicinessLevel: 3,
    originCountry: 'vietnam',
    rating: 10,
    category: 'Laksa',
  },
  {
    name: 'Wei Lih Instant Udon #53',
    brand: 'Wei Lih',
    spicinessLevel: 2,
    originCountry: 'vietnam',
    rating: 5,
    category: 'Instant Udon',
  },
  {
    name: 'Nissin Rice Noodles #54',
    brand: 'Nissin',
    spicinessLevel: 4,
    originCountry: 'philippines',
    rating: 5,
    category: 'Rice Noodles',
  },
  {
    name: 'Maggi Spicy Ramen #55',
    brand: 'Maggi',
    spicinessLevel: 1,
    originCountry: 'south_korea',
    rating: 7,
    category: 'Spicy Ramen',
  },
  {
    name: 'Wai Wai Curry Noodles #56',
    brand: 'Wai Wai',
    spicinessLevel: 3,
    originCountry: 'south_korea',
    rating: 9,
    category: 'Curry Noodles',
  },
  {
    name: "Ching's Secret Tom Yum #57",
    brand: "Ching's Secret",
    spicinessLevel: 2,
    originCountry: 'japan',
    rating: 9,
    category: 'Tom Yum',
  },
  {
    name: 'Maruchan Ramen #58',
    brand: 'Maruchan',
    spicinessLevel: 5,
    originCountry: 'taiwan',
    rating: 10,
    category: 'Ramen',
  },
  {
    name: 'Ottogi Rice Noodles #59',
    brand: 'Ottogi',
    spicinessLevel: 5,
    originCountry: 'china',
    rating: 6,
    category: 'Rice Noodles',
  },
  {
    name: 'Wai Wai Cup Noodles #60',
    brand: 'Wai Wai',
    spicinessLevel: 3,
    originCountry: 'singapore',
    rating: 5,
    category: 'Cup Noodles',
  },
  {
    name: 'Nissin Laksa #61',
    brand: 'Nissin',
    spicinessLevel: 1,
    originCountry: 'china',
    rating: 6,
    category: 'Laksa',
  },
  {
    name: 'Mama Tom Yum #62',
    brand: 'Mama',
    spicinessLevel: 2,
    originCountry: 'south_korea',
    rating: 6,
    category: 'Tom Yum',
  },
  {
    name: 'Wai Wai Spicy Ramen #63',
    brand: 'Wai Wai',
    spicinessLevel: 5,
    originCountry: 'malaysia',
    rating: 8,
    category: 'Spicy Ramen',
  },
  {
    name: 'Koka Spicy Ramen #64',
    brand: 'Koka',
    spicinessLevel: 3,
    originCountry: 'indonesia',
    rating: 8,
    category: 'Spicy Ramen',
  },
  {
    name: 'MyKuali Fried Noodles #65',
    brand: 'MyKuali',
    spicinessLevel: 5,
    originCountry: 'taiwan',
    rating: 6,
    category: 'Fried Noodles',
  },
  {
    name: 'Koka Tom Yum #66',
    brand: 'Koka',
    spicinessLevel: 2,
    originCountry: 'malaysia',
    rating: 7,
    category: 'Tom Yum',
  },
  {
    name: 'Paldo Cup Noodles #67',
    brand: 'Paldo',
    spicinessLevel: 3,
    originCountry: 'indonesia',
    rating: 5,
    category: 'Cup Noodles',
  },
  {
    name: 'Maruchan Rice Noodles #68',
    brand: 'Maruchan',
    spicinessLevel: 4,
    originCountry: 'philippines',
    rating: 8,
    category: 'Rice Noodles',
  },
  {
    name: 'Vifon Tom Yum #69',
    brand: 'Vifon',
    spicinessLevel: 4,
    originCountry: 'philippines',
    rating: 8,
    category: 'Tom Yum',
  },
  {
    name: 'Indomie Soba #70',
    brand: 'Indomie',
    spicinessLevel: 3,
    originCountry: 'malaysia',
    rating: 5,
    category: 'Soba',
  },
  {
    name: 'Maruchan Curry Noodles #71',
    brand: 'Maruchan',
    spicinessLevel: 1,
    originCountry: 'south_korea',
    rating: 6,
    category: 'Curry Noodles',
  },
  {
    name: 'Vifon Spicy Ramen #72',
    brand: 'Vifon',
    spicinessLevel: 4,
    originCountry: 'indonesia',
    rating: 8,
    category: 'Spicy Ramen',
  },
  {
    name: 'Wai Wai Fried Noodles #73',
    brand: 'Wai Wai',
    spicinessLevel: 4,
    originCountry: 'vietnam',
    rating: 5,
    category: 'Fried Noodles',
  },
  {
    name: 'Maggi Tom Yum #74',
    brand: 'Maggi',
    spicinessLevel: 4,
    originCountry: 'china',
    rating: 7,
    category: 'Tom Yum',
  },
  {
    name: 'Maggi Fried Noodles #75',
    brand: 'Maggi',
    spicinessLevel: 4,
    originCountry: 'indonesia',
    rating: 5,
    category: 'Fried Noodles',
  },
  {
    name: 'Nongshim Laksa #76',
    brand: 'Nongshim',
    spicinessLevel: 4,
    originCountry: 'vietnam',
    rating: 8,
    category: 'Laksa',
  },
  {
    name: 'Maggi Spicy Ramen #77',
    brand: 'Maggi',
    spicinessLevel: 4,
    originCountry: 'malaysia',
    rating: 5,
    category: 'Spicy Ramen',
  },
  {
    name: 'Tao Kae Noi Instant Udon #78',
    brand: 'Tao Kae Noi',
    spicinessLevel: 4,
    originCountry: 'taiwan',
    rating: 7,
    category: 'Instant Udon',
  },
  {
    name: 'Knorr Rice Noodles #79',
    brand: 'Knorr',
    spicinessLevel: 1,
    originCountry: 'philippines',
    rating: 9,
    category: 'Rice Noodles',
  },
  {
    name: 'Ottogi Laksa #80',
    brand: 'Ottogi',
    spicinessLevel: 3,
    originCountry: 'china',
    rating: 8,
    category: 'Laksa',
  },
  {
    name: 'Vifon Cup Noodles #81',
    brand: 'Vifon',
    spicinessLevel: 5,
    originCountry: 'thailand',
    rating: 7,
    category: 'Cup Noodles',
  },
  {
    name: 'Tao Kae Noi Laksa #82',
    brand: 'Tao Kae Noi',
    spicinessLevel: 5,
    originCountry: 'south_korea',
    rating: 5,
    category: 'Laksa',
  },
  {
    name: 'Wei Lih Fried Noodles #83',
    brand: 'Wei Lih',
    spicinessLevel: 2,
    originCountry: 'thailand',
    rating: 10,
    category: 'Fried Noodles',
  },
  {
    name: 'Mama Curry Noodles #84',
    brand: 'Mama',
    spicinessLevel: 3,
    originCountry: 'thailand',
    rating: 6,
    category: 'Curry Noodles',
  },
  {
    name: 'Nissin Tom Yum #85',
    brand: 'Nissin',
    spicinessLevel: 3,
    originCountry: 'japan',
    rating: 5,
    category: 'Tom Yum',
  },
  {
    name: 'Maruchan Spicy Ramen #86',
    brand: 'Maruchan',
    spicinessLevel: 1,
    originCountry: 'vietnam',
    rating: 5,
    category: 'Spicy Ramen',
  },
  {
    name: "Ching's Secret Laksa #87",
    brand: "Ching's Secret",
    spicinessLevel: 2,
    originCountry: 'thailand',
    rating: 6,
    category: 'Laksa',
  },
  {
    name: 'MyKuali Spicy Ramen #88',
    brand: 'MyKuali',
    spicinessLevel: 2,
    originCountry: 'philippines',
    rating: 5,
    category: 'Spicy Ramen',
  },
  {
    name: 'Tao Kae Noi Instant Udon #89',
    brand: 'Tao Kae Noi',
    spicinessLevel: 2,
    originCountry: 'south_korea',
    rating: 8,
    category: 'Instant Udon',
  },
  {
    name: 'Wei Lih Fried Noodles #90',
    brand: 'Wei Lih',
    spicinessLevel: 5,
    originCountry: 'taiwan',
    rating: 6,
    category: 'Fried Noodles',
  },
  {
    name: 'Mama Tom Yum #91',
    brand: 'Mama',
    spicinessLevel: 5,
    originCountry: 'taiwan',
    rating: 9,
    category: 'Tom Yum',
  },
  {
    name: 'Paldo Curry Noodles #92',
    brand: 'Paldo',
    spicinessLevel: 4,
    originCountry: 'taiwan',
    rating: 6,
    category: 'Curry Noodles',
  },
  {
    name: 'Wai Wai Fried Noodles #93',
    brand: 'Wai Wai',
    spicinessLevel: 1,
    originCountry: 'japan',
    rating: 10,
    category: 'Fried Noodles',
  },
  {
    name: 'Paldo Tom Yum #94',
    brand: 'Paldo',
    spicinessLevel: 1,
    originCountry: 'indonesia',
    rating: 5,
    category: 'Tom Yum',
  },
  {
    name: 'Mama Curry Noodles #95',
    brand: 'Mama',
    spicinessLevel: 3,
    originCountry: 'singapore',
    rating: 10,
    category: 'Curry Noodles',
  },
  {
    name: 'Maggi Spicy Ramen #96',
    brand: 'Maggi',
    spicinessLevel: 5,
    originCountry: 'philippines',
    rating: 9,
    category: 'Spicy Ramen',
  },
  {
    name: 'Tao Kae Noi Curry Noodles #97',
    brand: 'Tao Kae Noi',
    spicinessLevel: 4,
    originCountry: 'vietnam',
    rating: 10,
    category: 'Curry Noodles',
  },
  {
    name: 'Vifon Curry Noodles #98',
    brand: 'Vifon',
    spicinessLevel: 3,
    originCountry: 'philippines',
    rating: 8,
    category: 'Curry Noodles',
  },
  {
    name: 'Knorr Cup Noodles #99',
    brand: 'Knorr',
    spicinessLevel: 5,
    originCountry: 'japan',
    rating: 8,
    category: 'Cup Noodles',
  },
  {
    name: 'Maggi Tom Yum #100',
    brand: 'Maggi',
    spicinessLevel: 1,
    originCountry: 'philippines',
    rating: 10,
    category: 'Tom Yum',
  },
  {
    name: 'Wai Wai Curry Noodles #101',
    brand: 'Wai Wai',
    spicinessLevel: 2,
    originCountry: 'japan',
    rating: 8,
    category: 'Curry Noodles',
  },
  {
    name: 'Ottogi Instant Udon #102',
    brand: 'Ottogi',
    spicinessLevel: 5,
    originCountry: 'thailand',
    rating: 9,
    category: 'Instant Udon',
  },
  {
    name: 'MyKuali Soba #103',
    brand: 'MyKuali',
    spicinessLevel: 5,
    originCountry: 'malaysia',
    rating: 5,
    category: 'Soba',
  },
  {
    name: 'Mama Cup Noodles #104',
    brand: 'Mama',
    spicinessLevel: 4,
    originCountry: 'vietnam',
    rating: 9,
    category: 'Cup Noodles',
  },
  {
    name: 'Maggi Soba #105',
    brand: 'Maggi',
    spicinessLevel: 4,
    originCountry: 'taiwan',
    rating: 7,
    category: 'Soba',
  },
  {
    name: 'Vifon Spicy Ramen #106',
    brand: 'Vifon',
    spicinessLevel: 4,
    originCountry: 'taiwan',
    rating: 5,
    category: 'Spicy Ramen',
  },
  {
    name: 'Koka Rice Noodles #107',
    brand: 'Koka',
    spicinessLevel: 3,
    originCountry: 'china',
    rating: 5,
    category: 'Rice Noodles',
  },
  {
    name: 'Wai Wai Cup Noodles #108',
    brand: 'Wai Wai',
    spicinessLevel: 4,
    originCountry: 'japan',
    rating: 10,
    category: 'Cup Noodles',
  },
  {
    name: 'Knorr Cup Noodles #109',
    brand: 'Knorr',
    spicinessLevel: 4,
    originCountry: 'indonesia',
    rating: 8,
    category: 'Cup Noodles',
  },
  {
    name: "Ching's Secret Spicy Ramen #110",
    brand: "Ching's Secret",
    spicinessLevel: 1,
    originCountry: 'malaysia',
    rating: 6,
    category: 'Spicy Ramen',
  },
  {
    name: 'Koka Fried Noodles #111',
    brand: 'Koka',
    spicinessLevel: 3,
    originCountry: 'china',
    rating: 8,
    category: 'Fried Noodles',
  },
  {
    name: 'Wei Lih Cup Noodles #112',
    brand: 'Wei Lih',
    spicinessLevel: 3,
    originCountry: 'philippines',
    rating: 5,
    category: 'Cup Noodles',
  },
  {
    name: 'Samyang Instant Udon #113',
    brand: 'Samyang',
    spicinessLevel: 2,
    originCountry: 'indonesia',
    rating: 6,
    category: 'Instant Udon',
  },
  {
    name: "Ching's Secret Tom Yum #114",
    brand: "Ching's Secret",
    spicinessLevel: 2,
    originCountry: 'vietnam',
    rating: 8,
    category: 'Tom Yum',
  },
  {
    name: 'Koka Instant Udon #115',
    brand: 'Koka',
    spicinessLevel: 2,
    originCountry: 'taiwan',
    rating: 7,
    category: 'Instant Udon',
  },
  {
    name: 'Tao Kae Noi Cup Noodles #116',
    brand: 'Tao Kae Noi',
    spicinessLevel: 1,
    originCountry: 'indonesia',
    rating: 7,
    category: 'Cup Noodles',
  },
  {
    name: 'Nissin Curry Noodles #117',
    brand: 'Nissin',
    spicinessLevel: 5,
    originCountry: 'vietnam',
    rating: 8,
    category: 'Curry Noodles',
  },
  {
    name: 'Knorr Soba #118',
    brand: 'Knorr',
    spicinessLevel: 4,
    originCountry: 'vietnam',
    rating: 7,
    category: 'Soba',
  },
  {
    name: 'Indomie Fried Noodles #119',
    brand: 'Indomie',
    spicinessLevel: 2,
    originCountry: 'indonesia',
    rating: 5,
    category: 'Fried Noodles',
  },
  {
    name: 'Indomie Instant Udon #120',
    brand: 'Indomie',
    spicinessLevel: 1,
    originCountry: 'south_korea',
    rating: 9,
    category: 'Instant Udon',
  },
  {
    name: 'Paldo Soba #121',
    brand: 'Paldo',
    spicinessLevel: 3,
    originCountry: 'south_korea',
    rating: 5,
    category: 'Soba',
  },
  {
    name: 'Ottogi Cup Noodles #122',
    brand: 'Ottogi',
    spicinessLevel: 2,
    originCountry: 'japan',
    rating: 5,
    category: 'Cup Noodles',
  },
  {
    name: 'Koka Fried Noodles #123',
    brand: 'Koka',
    spicinessLevel: 2,
    originCountry: 'philippines',
    rating: 10,
    category: 'Fried Noodles',
  },
  {
    name: 'Koka Soba #124',
    brand: 'Koka',
    spicinessLevel: 1,
    originCountry: 'singapore',
    rating: 7,
    category: 'Soba',
  },
  {
    name: 'Maggi Ramen #125',
    brand: 'Maggi',
    spicinessLevel: 1,
    originCountry: 'south_korea',
    rating: 8,
    category: 'Ramen',
  },
  {
    name: 'Knorr Fried Noodles #126',
    brand: 'Knorr',
    spicinessLevel: 4,
    originCountry: 'malaysia',
    rating: 6,
    category: 'Fried Noodles',
  },
  {
    name: 'Koka Curry Noodles #127',
    brand: 'Koka',
    spicinessLevel: 4,
    originCountry: 'singapore',
    rating: 9,
    category: 'Curry Noodles',
  },
  {
    name: 'Nissin Spicy Ramen #128',
    brand: 'Nissin',
    spicinessLevel: 4,
    originCountry: 'vietnam',
    rating: 7,
    category: 'Spicy Ramen',
  },
  {
    name: 'Koka Tom Yum #129',
    brand: 'Koka',
    spicinessLevel: 4,
    originCountry: 'malaysia',
    rating: 10,
    category: 'Tom Yum',
  },
  {
    name: 'Knorr Curry Noodles #130',
    brand: 'Knorr',
    spicinessLevel: 5,
    originCountry: 'malaysia',
    rating: 5,
    category: 'Curry Noodles',
  },
  {
    name: 'Wai Wai Soba #131',
    brand: 'Wai Wai',
    spicinessLevel: 1,
    originCountry: 'china',
    rating: 10,
    category: 'Soba',
  },
  {
    name: 'Maruchan Fried Noodles #132',
    brand: 'Maruchan',
    spicinessLevel: 3,
    originCountry: 'singapore',
    rating: 9,
    category: 'Fried Noodles',
  },
  {
    name: 'Mama Ramen #133',
    brand: 'Mama',
    spicinessLevel: 4,
    originCountry: 'philippines',
    rating: 5,
    category: 'Ramen',
  },
  {
    name: 'Maggi Tom Yum #134',
    brand: 'Maggi',
    spicinessLevel: 3,
    originCountry: 'indonesia',
    rating: 8,
    category: 'Tom Yum',
  },
  {
    name: 'Knorr Tom Yum #135',
    brand: 'Knorr',
    spicinessLevel: 4,
    originCountry: 'malaysia',
    rating: 8,
    category: 'Tom Yum',
  },
  {
    name: 'Wei Lih Rice Noodles #136',
    brand: 'Wei Lih',
    spicinessLevel: 5,
    originCountry: 'taiwan',
    rating: 7,
    category: 'Rice Noodles',
  },
  {
    name: 'MyKuali Spicy Ramen #137',
    brand: 'MyKuali',
    spicinessLevel: 4,
    originCountry: 'vietnam',
    rating: 6,
    category: 'Spicy Ramen',
  },
  {
    name: 'Mama Laksa #138',
    brand: 'Mama',
    spicinessLevel: 4,
    originCountry: 'china',
    rating: 8,
    category: 'Laksa',
  },
  {
    name: 'Wai Wai Soba #139',
    brand: 'Wai Wai',
    spicinessLevel: 1,
    originCountry: 'vietnam',
    rating: 5,
    category: 'Soba',
  },
  {
    name: 'Mama Rice Noodles #140',
    brand: 'Mama',
    spicinessLevel: 2,
    originCountry: 'thailand',
    rating: 7,
    category: 'Rice Noodles',
  },
  {
    name: 'MyKuali Fried Noodles #141',
    brand: 'MyKuali',
    spicinessLevel: 1,
    originCountry: 'china',
    rating: 10,
    category: 'Fried Noodles',
  },
  {
    name: 'Wei Lih Laksa #142',
    brand: 'Wei Lih',
    spicinessLevel: 2,
    originCountry: 'vietnam',
    rating: 8,
    category: 'Laksa',
  },
  {
    name: 'MyKuali Tom Yum #143',
    brand: 'MyKuali',
    spicinessLevel: 3,
    originCountry: 'south_korea',
    rating: 7,
    category: 'Tom Yum',
  },
  {
    name: 'Mama Soba #144',
    brand: 'Mama',
    spicinessLevel: 1,
    originCountry: 'singapore',
    rating: 7,
    category: 'Soba',
  },
  {
    name: 'Mama Soba #145',
    brand: 'Mama',
    spicinessLevel: 3,
    originCountry: 'thailand',
    rating: 5,
    category: 'Soba',
  },
  {
    name: 'Ottogi Soba #146',
    brand: 'Ottogi',
    spicinessLevel: 5,
    originCountry: 'singapore',
    rating: 10,
    category: 'Soba',
  },
  {
    name: 'Mama Tom Yum #147',
    brand: 'Mama',
    spicinessLevel: 1,
    originCountry: 'vietnam',
    rating: 5,
    category: 'Tom Yum',
  },
  {
    name: 'Indomie Tom Yum #148',
    brand: 'Indomie',
    spicinessLevel: 3,
    originCountry: 'japan',
    rating: 10,
    category: 'Tom Yum',
  },
  {
    name: 'Maruchan Instant Udon #149',
    brand: 'Maruchan',
    spicinessLevel: 4,
    originCountry: 'thailand',
    rating: 9,
    category: 'Instant Udon',
  },
  {
    name: 'Maggi Fried Noodles #150',
    brand: 'Maggi',
    spicinessLevel: 2,
    originCountry: 'thailand',
    rating: 9,
    category: 'Fried Noodles',
  },
  {
    name: 'Mama Tom Yum #151',
    brand: 'Mama',
    spicinessLevel: 4,
    originCountry: 'vietnam',
    rating: 7,
    category: 'Tom Yum',
  },
  {
    name: 'Maggi Rice Noodles #152',
    brand: 'Maggi',
    spicinessLevel: 1,
    originCountry: 'malaysia',
    rating: 8,
    category: 'Rice Noodles',
  },
  {
    name: 'Maggi Soba #153',
    brand: 'Maggi',
    spicinessLevel: 3,
    originCountry: 'philippines',
    rating: 6,
    category: 'Soba',
  },
  {
    name: 'Indomie Laksa #154',
    brand: 'Indomie',
    spicinessLevel: 2,
    originCountry: 'japan',
    rating: 10,
    category: 'Laksa',
  },
  {
    name: 'Wei Lih Curry Noodles #155',
    brand: 'Wei Lih',
    spicinessLevel: 4,
    originCountry: 'singapore',
    rating: 9,
    category: 'Curry Noodles',
  },
  {
    name: 'Nongshim Rice Noodles #156',
    brand: 'Nongshim',
    spicinessLevel: 1,
    originCountry: 'philippines',
    rating: 5,
    category: 'Rice Noodles',
  },
  {
    name: 'Wai Wai Fried Noodles #157',
    brand: 'Wai Wai',
    spicinessLevel: 1,
    originCountry: 'singapore',
    rating: 5,
    category: 'Fried Noodles',
  },
  {
    name: 'Maggi Ramen #158',
    brand: 'Maggi',
    spicinessLevel: 5,
    originCountry: 'china',
    rating: 9,
    category: 'Ramen',
  },
  {
    name: 'Knorr Fried Noodles #159',
    brand: 'Knorr',
    spicinessLevel: 5,
    originCountry: 'vietnam',
    rating: 8,
    category: 'Fried Noodles',
  },
  {
    name: 'Nongshim Tom Yum #160',
    brand: 'Nongshim',
    spicinessLevel: 1,
    originCountry: 'taiwan',
    rating: 10,
    category: 'Tom Yum',
  },
  {
    name: 'Paldo Curry Noodles #161',
    brand: 'Paldo',
    spicinessLevel: 1,
    originCountry: 'taiwan',
    rating: 5,
    category: 'Curry Noodles',
  },
  {
    name: 'Mama Soba #162',
    brand: 'Mama',
    spicinessLevel: 4,
    originCountry: 'malaysia',
    rating: 9,
    category: 'Soba',
  },
  {
    name: 'Nissin Laksa #163',
    brand: 'Nissin',
    spicinessLevel: 3,
    originCountry: 'philippines',
    rating: 6,
    category: 'Laksa',
  },
  {
    name: 'Vifon Soba #164',
    brand: 'Vifon',
    spicinessLevel: 3,
    originCountry: 'china',
    rating: 5,
    category: 'Soba',
  },
  {
    name: 'Acecook Laksa #165',
    brand: 'Acecook',
    spicinessLevel: 4,
    originCountry: 'taiwan',
    rating: 10,
    category: 'Laksa',
  },
  {
    name: 'Vifon Tom Yum #166',
    brand: 'Vifon',
    spicinessLevel: 5,
    originCountry: 'china',
    rating: 9,
    category: 'Tom Yum',
  },
  {
    name: 'Maruchan Instant Udon #167',
    brand: 'Maruchan',
    spicinessLevel: 1,
    originCountry: 'vietnam',
    rating: 9,
    category: 'Instant Udon',
  },
  {
    name: 'Koka Tom Yum #168',
    brand: 'Koka',
    spicinessLevel: 1,
    originCountry: 'china',
    rating: 8,
    category: 'Tom Yum',
  },
  {
    name: 'Mama Ramen #169',
    brand: 'Mama',
    spicinessLevel: 2,
    originCountry: 'china',
    rating: 10,
    category: 'Ramen',
  },
  {
    name: 'Maruchan Cup Noodles #170',
    brand: 'Maruchan',
    spicinessLevel: 3,
    originCountry: 'vietnam',
    rating: 10,
    category: 'Cup Noodles',
  },
  {
    name: 'MyKuali Tom Yum #171',
    brand: 'MyKuali',
    spicinessLevel: 1,
    originCountry: 'china',
    rating: 9,
    category: 'Tom Yum',
  },
  {
    name: 'Acecook Laksa #172',
    brand: 'Acecook',
    spicinessLevel: 3,
    originCountry: 'singapore',
    rating: 6,
    category: 'Laksa',
  },
  {
    name: 'Wai Wai Instant Udon #173',
    brand: 'Wai Wai',
    spicinessLevel: 4,
    originCountry: 'malaysia',
    rating: 7,
    category: 'Instant Udon',
  },
  {
    name: 'Maggi Tom Yum #174',
    brand: 'Maggi',
    spicinessLevel: 5,
    originCountry: 'japan',
    rating: 10,
    category: 'Tom Yum',
  },
  {
    name: 'Maggi Cup Noodles #175',
    brand: 'Maggi',
    spicinessLevel: 2,
    originCountry: 'singapore',
    rating: 7,
    category: 'Cup Noodles',
  },
  {
    name: 'Mama Curry Noodles #176',
    brand: 'Mama',
    spicinessLevel: 2,
    originCountry: 'malaysia',
    rating: 6,
    category: 'Curry Noodles',
  },
  {
    name: 'Tao Kae Noi Ramen #177',
    brand: 'Tao Kae Noi',
    spicinessLevel: 2,
    originCountry: 'thailand',
    rating: 9,
    category: 'Ramen',
  },
  {
    name: 'Vifon Ramen #178',
    brand: 'Vifon',
    spicinessLevel: 2,
    originCountry: 'malaysia',
    rating: 8,
    category: 'Ramen',
  },
  {
    name: 'Tao Kae Noi Tom Yum #179',
    brand: 'Tao Kae Noi',
    spicinessLevel: 2,
    originCountry: 'taiwan',
    rating: 7,
    category: 'Tom Yum',
  },
  {
    name: 'Nongshim Rice Noodles #180',
    brand: 'Nongshim',
    spicinessLevel: 3,
    originCountry: 'china',
    rating: 8,
    category: 'Rice Noodles',
  },
  {
    name: 'Wei Lih Laksa #181',
    brand: 'Wei Lih',
    spicinessLevel: 3,
    originCountry: 'japan',
    rating: 6,
    category: 'Laksa',
  },
  {
    name: 'Mama Laksa #182',
    brand: 'Mama',
    spicinessLevel: 1,
    originCountry: 'indonesia',
    rating: 9,
    category: 'Laksa',
  },
  {
    name: 'Indomie Soba #183',
    brand: 'Indomie',
    spicinessLevel: 2,
    originCountry: 'vietnam',
    rating: 7,
    category: 'Soba',
  },
  {
    name: 'Samyang Curry Noodles #184',
    brand: 'Samyang',
    spicinessLevel: 2,
    originCountry: 'china',
    rating: 9,
    category: 'Curry Noodles',
  },
  {
    name: 'Koka Soba #185',
    brand: 'Koka',
    spicinessLevel: 4,
    originCountry: 'malaysia',
    rating: 7,
    category: 'Soba',
  },
  {
    name: 'Acecook Instant Udon #186',
    brand: 'Acecook',
    spicinessLevel: 4,
    originCountry: 'philippines',
    rating: 10,
    category: 'Instant Udon',
  },
  {
    name: 'Nissin Ramen #187',
    brand: 'Nissin',
    spicinessLevel: 5,
    originCountry: 'china',
    rating: 8,
    category: 'Ramen',
  },
  {
    name: "Ching's Secret Soba #188",
    brand: "Ching's Secret",
    spicinessLevel: 3,
    originCountry: 'malaysia',
    rating: 10,
    category: 'Soba',
  },
  {
    name: 'Wei Lih Tom Yum #189',
    brand: 'Wei Lih',
    spicinessLevel: 5,
    originCountry: 'china',
    rating: 6,
    category: 'Tom Yum',
  },
  {
    name: 'Tao Kae Noi Laksa #190',
    brand: 'Tao Kae Noi',
    spicinessLevel: 1,
    originCountry: 'philippines',
    rating: 9,
    category: 'Laksa',
  },
  {
    name: 'Mama Cup Noodles #191',
    brand: 'Mama',
    spicinessLevel: 2,
    originCountry: 'china',
    rating: 8,
    category: 'Cup Noodles',
  },
  {
    name: 'Indomie Tom Yum #192',
    brand: 'Indomie',
    spicinessLevel: 4,
    originCountry: 'indonesia',
    rating: 8,
    category: 'Tom Yum',
  },
  {
    name: 'Knorr Fried Noodles #193',
    brand: 'Knorr',
    spicinessLevel: 3,
    originCountry: 'japan',
    rating: 9,
    category: 'Fried Noodles',
  },
  {
    name: 'Tao Kae Noi Ramen #194',
    brand: 'Tao Kae Noi',
    spicinessLevel: 1,
    originCountry: 'south_korea',
    rating: 5,
    category: 'Ramen',
  },
  {
    name: 'Mama Soba #195',
    brand: 'Mama',
    spicinessLevel: 5,
    originCountry: 'malaysia',
    rating: 5,
    category: 'Soba',
  },
  {
    name: 'Mama Curry Noodles #196',
    brand: 'Mama',
    spicinessLevel: 2,
    originCountry: 'singapore',
    rating: 7,
    category: 'Curry Noodles',
  },
  {
    name: 'MyKuali Tom Yum #197',
    brand: 'MyKuali',
    spicinessLevel: 3,
    originCountry: 'south_korea',
    rating: 9,
    category: 'Tom Yum',
  },
  {
    name: 'Nissin Spicy Ramen #198',
    brand: 'Nissin',
    spicinessLevel: 1,
    originCountry: 'japan',
    rating: 5,
    category: 'Spicy Ramen',
  },
  {
    name: 'Ottogi Soba #199',
    brand: 'Ottogi',
    spicinessLevel: 1,
    originCountry: 'china',
    rating: 8,
    category: 'Soba',
  },
  {
    name: "Ching's Secret Cup Noodles #200",
    brand: "Ching's Secret",
    spicinessLevel: 4,
    originCountry: 'malaysia',
    rating: 8,
    category: 'Cup Noodles',
  },
  {
    name: 'Mama Fried Noodles #201',
    brand: 'Mama',
    spicinessLevel: 5,
    originCountry: 'singapore',
    rating: 6,
    category: 'Fried Noodles',
  },
  {
    name: 'Wei Lih Spicy Ramen #202',
    brand: 'Wei Lih',
    spicinessLevel: 1,
    originCountry: 'thailand',
    rating: 7,
    category: 'Spicy Ramen',
  },
  {
    name: 'Vifon Laksa #203',
    brand: 'Vifon',
    spicinessLevel: 4,
    originCountry: 'thailand',
    rating: 9,
    category: 'Laksa',
  },
  {
    name: 'Maggi Soba #204',
    brand: 'Maggi',
    spicinessLevel: 4,
    originCountry: 'south_korea',
    rating: 9,
    category: 'Soba',
  },
  {
    name: 'Koka Cup Noodles #205',
    brand: 'Koka',
    spicinessLevel: 1,
    originCountry: 'singapore',
    rating: 10,
    category: 'Cup Noodles',
  },
  {
    name: 'Vifon Soba #206',
    brand: 'Vifon',
    spicinessLevel: 4,
    originCountry: 'indonesia',
    rating: 10,
    category: 'Soba',
  },
  {
    name: 'Knorr Soba #207',
    brand: 'Knorr',
    spicinessLevel: 3,
    originCountry: 'japan',
    rating: 5,
    category: 'Soba',
  },
  {
    name: 'Ottogi Curry Noodles #208',
    brand: 'Ottogi',
    spicinessLevel: 2,
    originCountry: 'singapore',
    rating: 8,
    category: 'Curry Noodles',
  },
  {
    name: 'Maggi Cup Noodles #209',
    brand: 'Maggi',
    spicinessLevel: 2,
    originCountry: 'malaysia',
    rating: 10,
    category: 'Cup Noodles',
  },
  {
    name: "Ching's Secret Cup Noodles #210",
    brand: "Ching's Secret",
    spicinessLevel: 2,
    originCountry: 'china',
    rating: 6,
    category: 'Cup Noodles',
  },
  {
    name: 'Knorr Cup Noodles #211',
    brand: 'Knorr',
    spicinessLevel: 4,
    originCountry: 'vietnam',
    rating: 10,
    category: 'Cup Noodles',
  },
  {
    name: 'Samyang Cup Noodles #212',
    brand: 'Samyang',
    spicinessLevel: 4,
    originCountry: 'taiwan',
    rating: 9,
    category: 'Cup Noodles',
  },
  {
    name: 'Samyang Curry Noodles #213',
    brand: 'Samyang',
    spicinessLevel: 2,
    originCountry: 'taiwan',
    rating: 5,
    category: 'Curry Noodles',
  },
  {
    name: 'Ottogi Soba #214',
    brand: 'Ottogi',
    spicinessLevel: 1,
    originCountry: 'philippines',
    rating: 5,
    category: 'Soba',
  },
  {
    name: 'MyKuali Ramen #215',
    brand: 'MyKuali',
    spicinessLevel: 1,
    originCountry: 'taiwan',
    rating: 9,
    category: 'Ramen',
  },
  {
    name: 'Nongshim Fried Noodles #216',
    brand: 'Nongshim',
    spicinessLevel: 4,
    originCountry: 'south_korea',
    rating: 8,
    category: 'Fried Noodles',
  },
  {
    name: 'Paldo Cup Noodles #217',
    brand: 'Paldo',
    spicinessLevel: 5,
    originCountry: 'japan',
    rating: 7,
    category: 'Cup Noodles',
  },
  {
    name: 'Knorr Fried Noodles #218',
    brand: 'Knorr',
    spicinessLevel: 2,
    originCountry: 'philippines',
    rating: 6,
    category: 'Fried Noodles',
  },
  {
    name: 'Wai Wai Tom Yum #219',
    brand: 'Wai Wai',
    spicinessLevel: 2,
    originCountry: 'philippines',
    rating: 8,
    category: 'Tom Yum',
  },
  {
    name: 'Mama Instant Udon #220',
    brand: 'Mama',
    spicinessLevel: 5,
    originCountry: 'south_korea',
    rating: 10,
    category: 'Instant Udon',
  },
  {
    name: "Ching's Secret Spicy Ramen #221",
    brand: "Ching's Secret",
    spicinessLevel: 5,
    originCountry: 'indonesia',
    rating: 8,
    category: 'Spicy Ramen',
  },
  {
    name: 'Tao Kae Noi Curry Noodles #222',
    brand: 'Tao Kae Noi',
    spicinessLevel: 1,
    originCountry: 'singapore',
    rating: 9,
    category: 'Curry Noodles',
  },
  {
    name: 'Wei Lih Curry Noodles #223',
    brand: 'Wei Lih',
    spicinessLevel: 3,
    originCountry: 'malaysia',
    rating: 8,
    category: 'Curry Noodles',
  },
  {
    name: 'Mama Spicy Ramen #224',
    brand: 'Mama',
    spicinessLevel: 1,
    originCountry: 'philippines',
    rating: 6,
    category: 'Spicy Ramen',
  },
  {
    name: 'Ottogi Instant Udon #225',
    brand: 'Ottogi',
    spicinessLevel: 4,
    originCountry: 'malaysia',
    rating: 6,
    category: 'Instant Udon',
  },
  {
    name: 'Maggi Soba #226',
    brand: 'Maggi',
    spicinessLevel: 2,
    originCountry: 'singapore',
    rating: 6,
    category: 'Soba',
  },
  {
    name: 'Maruchan Ramen #227',
    brand: 'Maruchan',
    spicinessLevel: 2,
    originCountry: 'philippines',
    rating: 8,
    category: 'Ramen',
  },
  {
    name: 'Nongshim Soba #228',
    brand: 'Nongshim',
    spicinessLevel: 5,
    originCountry: 'taiwan',
    rating: 8,
    category: 'Soba',
  },
  {
    name: 'Mama Laksa #229',
    brand: 'Mama',
    spicinessLevel: 5,
    originCountry: 'japan',
    rating: 6,
    category: 'Laksa',
  },
  {
    name: 'Koka Soba #230',
    brand: 'Koka',
    spicinessLevel: 3,
    originCountry: 'singapore',
    rating: 5,
    category: 'Soba',
  },
  {
    name: 'Indomie Laksa #231',
    brand: 'Indomie',
    spicinessLevel: 1,
    originCountry: 'china',
    rating: 8,
    category: 'Laksa',
  },
  {
    name: 'Wai Wai Curry Noodles #232',
    brand: 'Wai Wai',
    spicinessLevel: 2,
    originCountry: 'china',
    rating: 6,
    category: 'Curry Noodles',
  },
  {
    name: 'Maggi Tom Yum #233',
    brand: 'Maggi',
    spicinessLevel: 4,
    originCountry: 'vietnam',
    rating: 8,
    category: 'Tom Yum',
  },
  {
    name: 'Nissin Fried Noodles #234',
    brand: 'Nissin',
    spicinessLevel: 4,
    originCountry: 'japan',
    rating: 10,
    category: 'Fried Noodles',
  },
  {
    name: 'Maruchan Tom Yum #235',
    brand: 'Maruchan',
    spicinessLevel: 4,
    originCountry: 'thailand',
    rating: 5,
    category: 'Tom Yum',
  },
  {
    name: 'Wei Lih Rice Noodles #236',
    brand: 'Wei Lih',
    spicinessLevel: 3,
    originCountry: 'philippines',
    rating: 5,
    category: 'Rice Noodles',
  },
  {
    name: 'Vifon Laksa #237',
    brand: 'Vifon',
    spicinessLevel: 2,
    originCountry: 'malaysia',
    rating: 9,
    category: 'Laksa',
  },
  {
    name: 'Vifon Cup Noodles #238',
    brand: 'Vifon',
    spicinessLevel: 4,
    originCountry: 'china',
    rating: 8,
    category: 'Cup Noodles',
  },
  {
    name: 'Ottogi Instant Udon #239',
    brand: 'Ottogi',
    spicinessLevel: 2,
    originCountry: 'south_korea',
    rating: 9,
    category: 'Instant Udon',
  },
  {
    name: 'Maruchan Rice Noodles #240',
    brand: 'Maruchan',
    spicinessLevel: 4,
    originCountry: 'thailand',
    rating: 6,
    category: 'Rice Noodles',
  },
  {
    name: 'Ottogi Ramen #241',
    brand: 'Ottogi',
    spicinessLevel: 1,
    originCountry: 'china',
    rating: 9,
    category: 'Ramen',
  },
  {
    name: 'Samyang Cup Noodles #242',
    brand: 'Samyang',
    spicinessLevel: 5,
    originCountry: 'china',
    rating: 8,
    category: 'Cup Noodles',
  },
  {
    name: 'Paldo Soba #243',
    brand: 'Paldo',
    spicinessLevel: 3,
    originCountry: 'taiwan',
    rating: 5,
    category: 'Soba',
  },
  {
    name: 'Samyang Ramen #244',
    brand: 'Samyang',
    spicinessLevel: 4,
    originCountry: 'vietnam',
    rating: 9,
    category: 'Ramen',
  },
  {
    name: 'Maggi Laksa #245',
    brand: 'Maggi',
    spicinessLevel: 5,
    originCountry: 'philippines',
    rating: 7,
    category: 'Laksa',
  },
  {
    name: 'Nissin Laksa #246',
    brand: 'Nissin',
    spicinessLevel: 2,
    originCountry: 'malaysia',
    rating: 7,
    category: 'Laksa',
  },
  {
    name: 'Nongshim Fried Noodles #247',
    brand: 'Nongshim',
    spicinessLevel: 2,
    originCountry: 'china',
    rating: 6,
    category: 'Fried Noodles',
  },
  {
    name: 'Koka Ramen #248',
    brand: 'Koka',
    spicinessLevel: 2,
    originCountry: 'thailand',
    rating: 6,
    category: 'Ramen',
  },
  {
    name: 'Mama Spicy Ramen #249',
    brand: 'Mama',
    spicinessLevel: 2,
    originCountry: 'thailand',
    rating: 6,
    category: 'Spicy Ramen',
  },
  {
    name: 'Samyang Tom Yum #250',
    brand: 'Samyang',
    spicinessLevel: 3,
    originCountry: 'china',
    rating: 8,
    category: 'Tom Yum',
  },
  {
    name: 'Tao Kae Noi Instant Udon #251',
    brand: 'Tao Kae Noi',
    spicinessLevel: 4,
    originCountry: 'malaysia',
    rating: 9,
    category: 'Instant Udon',
  },
  {
    name: 'Wai Wai Ramen #252',
    brand: 'Wai Wai',
    spicinessLevel: 5,
    originCountry: 'thailand',
    rating: 9,
    category: 'Ramen',
  },
  {
    name: 'Samyang Ramen #253',
    brand: 'Samyang',
    spicinessLevel: 2,
    originCountry: 'taiwan',
    rating: 7,
    category: 'Ramen',
  },
  {
    name: 'Vifon Spicy Ramen #254',
    brand: 'Vifon',
    spicinessLevel: 4,
    originCountry: 'japan',
    rating: 10,
    category: 'Spicy Ramen',
  },
  {
    name: 'Wei Lih Rice Noodles #255',
    brand: 'Wei Lih',
    spicinessLevel: 3,
    originCountry: 'singapore',
    rating: 10,
    category: 'Rice Noodles',
  },
  {
    name: 'Tao Kae Noi Soba #256',
    brand: 'Tao Kae Noi',
    spicinessLevel: 1,
    originCountry: 'indonesia',
    rating: 7,
    category: 'Soba',
  },
  {
    name: 'Paldo Soba #257',
    brand: 'Paldo',
    spicinessLevel: 2,
    originCountry: 'malaysia',
    rating: 10,
    category: 'Soba',
  },
  {
    name: "Ching's Secret Fried Noodles #258",
    brand: "Ching's Secret",
    spicinessLevel: 1,
    originCountry: 'thailand',
    rating: 7,
    category: 'Fried Noodles',
  },
  {
    name: 'Wai Wai Curry Noodles #259',
    brand: 'Wai Wai',
    spicinessLevel: 5,
    originCountry: 'philippines',
    rating: 5,
    category: 'Curry Noodles',
  },
  {
    name: 'Knorr Fried Noodles #260',
    brand: 'Knorr',
    spicinessLevel: 5,
    originCountry: 'indonesia',
    rating: 9,
    category: 'Fried Noodles',
  },
  {
    name: 'Koka Ramen #261',
    brand: 'Koka',
    spicinessLevel: 2,
    originCountry: 'indonesia',
    rating: 9,
    category: 'Ramen',
  },
  {
    name: 'Wei Lih Laksa #262',
    brand: 'Wei Lih',
    spicinessLevel: 2,
    originCountry: 'indonesia',
    rating: 6,
    category: 'Laksa',
  },
  {
    name: "Ching's Secret Laksa #263",
    brand: "Ching's Secret",
    spicinessLevel: 1,
    originCountry: 'vietnam',
    rating: 5,
    category: 'Laksa',
  },
  {
    name: 'Knorr Cup Noodles #264',
    brand: 'Knorr',
    spicinessLevel: 2,
    originCountry: 'thailand',
    rating: 8,
    category: 'Cup Noodles',
  },
  {
    name: 'Tao Kae Noi Ramen #265',
    brand: 'Tao Kae Noi',
    spicinessLevel: 5,
    originCountry: 'philippines',
    rating: 9,
    category: 'Ramen',
  },
  {
    name: 'Acecook Soba #266',
    brand: 'Acecook',
    spicinessLevel: 2,
    originCountry: 'thailand',
    rating: 8,
    category: 'Soba',
  },
  {
    name: 'Nissin Tom Yum #267',
    brand: 'Nissin',
    spicinessLevel: 1,
    originCountry: 'japan',
    rating: 8,
    category: 'Tom Yum',
  },
  {
    name: 'Koka Ramen #268',
    brand: 'Koka',
    spicinessLevel: 4,
    originCountry: 'thailand',
    rating: 10,
    category: 'Ramen',
  },
  {
    name: 'Ottogi Cup Noodles #269',
    brand: 'Ottogi',
    spicinessLevel: 3,
    originCountry: 'malaysia',
    rating: 9,
    category: 'Cup Noodles',
  },
  {
    name: 'MyKuali Spicy Ramen #270',
    brand: 'MyKuali',
    spicinessLevel: 2,
    originCountry: 'thailand',
    rating: 6,
    category: 'Spicy Ramen',
  },
  {
    name: 'Maruchan Soba #271',
    brand: 'Maruchan',
    spicinessLevel: 4,
    originCountry: 'singapore',
    rating: 10,
    category: 'Soba',
  },
  {
    name: 'Koka Soba #272',
    brand: 'Koka',
    spicinessLevel: 1,
    originCountry: 'thailand',
    rating: 5,
    category: 'Soba',
  },
  {
    name: 'Wei Lih Curry Noodles #273',
    brand: 'Wei Lih',
    spicinessLevel: 1,
    originCountry: 'taiwan',
    rating: 9,
    category: 'Curry Noodles',
  },
  {
    name: 'Acecook Rice Noodles #274',
    brand: 'Acecook',
    spicinessLevel: 3,
    originCountry: 'vietnam',
    rating: 5,
    category: 'Rice Noodles',
  },
  {
    name: 'Mama Cup Noodles #275',
    brand: 'Mama',
    spicinessLevel: 2,
    originCountry: 'singapore',
    rating: 9,
    category: 'Cup Noodles',
  },
  {
    name: 'Knorr Soba #276',
    brand: 'Knorr',
    spicinessLevel: 3,
    originCountry: 'south_korea',
    rating: 6,
    category: 'Soba',
  },
  {
    name: 'Paldo Tom Yum #277',
    brand: 'Paldo',
    spicinessLevel: 2,
    originCountry: 'taiwan',
    rating: 10,
    category: 'Tom Yum',
  },
  {
    name: "Ching's Secret Ramen #278",
    brand: "Ching's Secret",
    spicinessLevel: 4,
    originCountry: 'malaysia',
    rating: 6,
    category: 'Ramen',
  },
  {
    name: 'Vifon Laksa #279',
    brand: 'Vifon',
    spicinessLevel: 3,
    originCountry: 'malaysia',
    rating: 9,
    category: 'Laksa',
  },
  {
    name: 'Mama Laksa #280',
    brand: 'Mama',
    spicinessLevel: 1,
    originCountry: 'south_korea',
    rating: 6,
    category: 'Laksa',
  },
  {
    name: 'Koka Soba #281',
    brand: 'Koka',
    spicinessLevel: 5,
    originCountry: 'philippines',
    rating: 6,
    category: 'Soba',
  },
  {
    name: 'Acecook Spicy Ramen #282',
    brand: 'Acecook',
    spicinessLevel: 2,
    originCountry: 'taiwan',
    rating: 8,
    category: 'Spicy Ramen',
  },
  {
    name: 'Mama Spicy Ramen #283',
    brand: 'Mama',
    spicinessLevel: 4,
    originCountry: 'indonesia',
    rating: 8,
    category: 'Spicy Ramen',
  },
  {
    name: 'Koka Rice Noodles #284',
    brand: 'Koka',
    spicinessLevel: 1,
    originCountry: 'china',
    rating: 10,
    category: 'Rice Noodles',
  },
  {
    name: 'Indomie Laksa #285',
    brand: 'Indomie',
    spicinessLevel: 5,
    originCountry: 'thailand',
    rating: 7,
    category: 'Laksa',
  },
  {
    name: 'Wei Lih Laksa #286',
    brand: 'Wei Lih',
    spicinessLevel: 4,
    originCountry: 'thailand',
    rating: 9,
    category: 'Laksa',
  },
  {
    name: 'Wai Wai Soba #287',
    brand: 'Wai Wai',
    spicinessLevel: 4,
    originCountry: 'japan',
    rating: 7,
    category: 'Soba',
  },
  {
    name: 'Vifon Tom Yum #288',
    brand: 'Vifon',
    spicinessLevel: 3,
    originCountry: 'taiwan',
    rating: 7,
    category: 'Tom Yum',
  },
  {
    name: 'Maruchan Curry Noodles #289',
    brand: 'Maruchan',
    spicinessLevel: 4,
    originCountry: 'indonesia',
    rating: 5,
    category: 'Curry Noodles',
  },
  {
    name: 'Maggi Tom Yum #290',
    brand: 'Maggi',
    spicinessLevel: 3,
    originCountry: 'malaysia',
    rating: 6,
    category: 'Tom Yum',
  },
  {
    name: 'Maruchan Tom Yum #291',
    brand: 'Maruchan',
    spicinessLevel: 3,
    originCountry: 'philippines',
    rating: 10,
    category: 'Tom Yum',
  },
  {
    name: 'Wai Wai Tom Yum #292',
    brand: 'Wai Wai',
    spicinessLevel: 5,
    originCountry: 'singapore',
    rating: 8,
    category: 'Tom Yum',
  },
  {
    name: 'Acecook Spicy Ramen #293',
    brand: 'Acecook',
    spicinessLevel: 1,
    originCountry: 'malaysia',
    rating: 8,
    category: 'Spicy Ramen',
  },
  {
    name: 'Wai Wai Curry Noodles #294',
    brand: 'Wai Wai',
    spicinessLevel: 1,
    originCountry: 'malaysia',
    rating: 9,
    category: 'Curry Noodles',
  },
  {
    name: 'Samyang Spicy Ramen #295',
    brand: 'Samyang',
    spicinessLevel: 1,
    originCountry: 'malaysia',
    rating: 10,
    category: 'Spicy Ramen',
  },
  {
    name: 'Koka Cup Noodles #296',
    brand: 'Koka',
    spicinessLevel: 2,
    originCountry: 'singapore',
    rating: 7,
    category: 'Cup Noodles',
  },
  {
    name: 'Acecook Soba #297',
    brand: 'Acecook',
    spicinessLevel: 2,
    originCountry: 'japan',
    rating: 8,
    category: 'Soba',
  },
  {
    name: 'Mama Ramen #298',
    brand: 'Mama',
    spicinessLevel: 1,
    originCountry: 'indonesia',
    rating: 8,
    category: 'Ramen',
  },
  {
    name: 'Koka Soba #299',
    brand: 'Koka',
    spicinessLevel: 1,
    originCountry: 'thailand',
    rating: 6,
    category: 'Soba',
  },
  {
    name: 'Nissin Curry Noodles #300',
    brand: 'Nissin',
    spicinessLevel: 2,
    originCountry: 'thailand',
    rating: 9,
    category: 'Curry Noodles',
  },
  {
    name: 'Paldo Rice Noodles #301',
    brand: 'Paldo',
    spicinessLevel: 2,
    originCountry: 'singapore',
    rating: 10,
    category: 'Rice Noodles',
  },
  {
    name: 'Koka Soba #302',
    brand: 'Koka',
    spicinessLevel: 5,
    originCountry: 'philippines',
    rating: 10,
    category: 'Soba',
  },
  {
    name: 'Maggi Laksa #303',
    brand: 'Maggi',
    spicinessLevel: 2,
    originCountry: 'malaysia',
    rating: 6,
    category: 'Laksa',
  },
  {
    name: 'Vifon Spicy Ramen #304',
    brand: 'Vifon',
    spicinessLevel: 2,
    originCountry: 'indonesia',
    rating: 7,
    category: 'Spicy Ramen',
  },
  {
    name: 'MyKuali Soba #305',
    brand: 'MyKuali',
    spicinessLevel: 2,
    originCountry: 'malaysia',
    rating: 10,
    category: 'Soba',
  },
  {
    name: 'Maruchan Cup Noodles #306',
    brand: 'Maruchan',
    spicinessLevel: 3,
    originCountry: 'south_korea',
    rating: 5,
    category: 'Cup Noodles',
  },
  {
    name: 'Vifon Soba #307',
    brand: 'Vifon',
    spicinessLevel: 1,
    originCountry: 'south_korea',
    rating: 6,
    category: 'Soba',
  },
  {
    name: 'Mama Instant Udon #308',
    brand: 'Mama',
    spicinessLevel: 3,
    originCountry: 'china',
    rating: 10,
    category: 'Instant Udon',
  },
  {
    name: 'Koka Instant Udon #309',
    brand: 'Koka',
    spicinessLevel: 1,
    originCountry: 'japan',
    rating: 6,
    category: 'Instant Udon',
  },
  {
    name: 'Nongshim Instant Udon #310',
    brand: 'Nongshim',
    spicinessLevel: 5,
    originCountry: 'indonesia',
    rating: 6,
    category: 'Instant Udon',
  },
  {
    name: 'Maruchan Cup Noodles #311',
    brand: 'Maruchan',
    spicinessLevel: 4,
    originCountry: 'south_korea',
    rating: 5,
    category: 'Cup Noodles',
  },
  {
    name: 'Acecook Instant Udon #312',
    brand: 'Acecook',
    spicinessLevel: 3,
    originCountry: 'china',
    rating: 5,
    category: 'Instant Udon',
  },
  {
    name: 'Wai Wai Soba #313',
    brand: 'Wai Wai',
    spicinessLevel: 3,
    originCountry: 'singapore',
    rating: 6,
    category: 'Soba',
  },
  {
    name: 'Wei Lih Cup Noodles #314',
    brand: 'Wei Lih',
    spicinessLevel: 4,
    originCountry: 'philippines',
    rating: 6,
    category: 'Cup Noodles',
  },
  {
    name: 'Knorr Spicy Ramen #315',
    brand: 'Knorr',
    spicinessLevel: 3,
    originCountry: 'vietnam',
    rating: 9,
    category: 'Spicy Ramen',
  },
  {
    name: 'Maggi Curry Noodles #316',
    brand: 'Maggi',
    spicinessLevel: 3,
    originCountry: 'thailand',
    rating: 6,
    category: 'Curry Noodles',
  },
  {
    name: 'Wei Lih Spicy Ramen #317',
    brand: 'Wei Lih',
    spicinessLevel: 4,
    originCountry: 'china',
    rating: 8,
    category: 'Spicy Ramen',
  },
  {
    name: 'Wai Wai Ramen #318',
    brand: 'Wai Wai',
    spicinessLevel: 1,
    originCountry: 'japan',
    rating: 7,
    category: 'Ramen',
  },
  {
    name: 'Knorr Fried Noodles #319',
    brand: 'Knorr',
    spicinessLevel: 5,
    originCountry: 'philippines',
    rating: 9,
    category: 'Fried Noodles',
  },
  {
    name: 'Acecook Instant Udon #320',
    brand: 'Acecook',
    spicinessLevel: 3,
    originCountry: 'vietnam',
    rating: 7,
    category: 'Instant Udon',
  },
  {
    name: 'MyKuali Soba #321',
    brand: 'MyKuali',
    spicinessLevel: 3,
    originCountry: 'singapore',
    rating: 8,
    category: 'Soba',
  },
  {
    name: 'Samyang Ramen #322',
    brand: 'Samyang',
    spicinessLevel: 3,
    originCountry: 'thailand',
    rating: 5,
    category: 'Ramen',
  },
  {
    name: 'Maggi Laksa #323',
    brand: 'Maggi',
    spicinessLevel: 3,
    originCountry: 'taiwan',
    rating: 5,
    category: 'Laksa',
  },
  {
    name: 'Mama Fried Noodles #324',
    brand: 'Mama',
    spicinessLevel: 2,
    originCountry: 'japan',
    rating: 8,
    category: 'Fried Noodles',
  },
  {
    name: 'Tao Kae Noi Cup Noodles #325',
    brand: 'Tao Kae Noi',
    spicinessLevel: 1,
    originCountry: 'singapore',
    rating: 6,
    category: 'Cup Noodles',
  },
  {
    name: 'Nissin Laksa #326',
    brand: 'Nissin',
    spicinessLevel: 2,
    originCountry: 'china',
    rating: 8,
    category: 'Laksa',
  },
  {
    name: 'Indomie Laksa #327',
    brand: 'Indomie',
    spicinessLevel: 5,
    originCountry: 'south_korea',
    rating: 5,
    category: 'Laksa',
  },
  {
    name: 'Paldo Tom Yum #328',
    brand: 'Paldo',
    spicinessLevel: 5,
    originCountry: 'philippines',
    rating: 7,
    category: 'Tom Yum',
  },
  {
    name: 'Indomie Cup Noodles #329',
    brand: 'Indomie',
    spicinessLevel: 2,
    originCountry: 'south_korea',
    rating: 7,
    category: 'Cup Noodles',
  },
  {
    name: 'Indomie Instant Udon #330',
    brand: 'Indomie',
    spicinessLevel: 5,
    originCountry: 'vietnam',
    rating: 9,
    category: 'Instant Udon',
  },
  {
    name: 'Indomie Rice Noodles #331',
    brand: 'Indomie',
    spicinessLevel: 3,
    originCountry: 'malaysia',
    rating: 7,
    category: 'Rice Noodles',
  },
  {
    name: 'Maruchan Curry Noodles #332',
    brand: 'Maruchan',
    spicinessLevel: 3,
    originCountry: 'japan',
    rating: 5,
    category: 'Curry Noodles',
  },
  {
    name: 'Maruchan Laksa #333',
    brand: 'Maruchan',
    spicinessLevel: 1,
    originCountry: 'philippines',
    rating: 7,
    category: 'Laksa',
  },
  {
    name: 'Samyang Fried Noodles #334',
    brand: 'Samyang',
    spicinessLevel: 5,
    originCountry: 'singapore',
    rating: 7,
    category: 'Fried Noodles',
  },
  {
    name: 'Tao Kae Noi Instant Udon #335',
    brand: 'Tao Kae Noi',
    spicinessLevel: 2,
    originCountry: 'vietnam',
    rating: 8,
    category: 'Instant Udon',
  },
  {
    name: 'Maggi Rice Noodles #336',
    brand: 'Maggi',
    spicinessLevel: 4,
    originCountry: 'taiwan',
    rating: 7,
    category: 'Rice Noodles',
  },
  {
    name: 'Wei Lih Fried Noodles #337',
    brand: 'Wei Lih',
    spicinessLevel: 4,
    originCountry: 'japan',
    rating: 8,
    category: 'Fried Noodles',
  },
  {
    name: 'Acecook Ramen #338',
    brand: 'Acecook',
    spicinessLevel: 2,
    originCountry: 'malaysia',
    rating: 8,
    category: 'Ramen',
  },
  {
    name: 'Nissin Laksa #339',
    brand: 'Nissin',
    spicinessLevel: 2,
    originCountry: 'china',
    rating: 9,
    category: 'Laksa',
  },
  {
    name: 'Paldo Fried Noodles #340',
    brand: 'Paldo',
    spicinessLevel: 3,
    originCountry: 'singapore',
    rating: 5,
    category: 'Fried Noodles',
  },
  {
    name: 'Ottogi Tom Yum #341',
    brand: 'Ottogi',
    spicinessLevel: 5,
    originCountry: 'vietnam',
    rating: 10,
    category: 'Tom Yum',
  },
  {
    name: 'Samyang Cup Noodles #342',
    brand: 'Samyang',
    spicinessLevel: 3,
    originCountry: 'taiwan',
    rating: 5,
    category: 'Cup Noodles',
  },
  {
    name: 'Nongshim Spicy Ramen #343',
    brand: 'Nongshim',
    spicinessLevel: 4,
    originCountry: 'malaysia',
    rating: 8,
    category: 'Spicy Ramen',
  },
  {
    name: 'Ottogi Spicy Ramen #344',
    brand: 'Ottogi',
    spicinessLevel: 4,
    originCountry: 'south_korea',
    rating: 10,
    category: 'Spicy Ramen',
  },
  {
    name: 'Wei Lih Curry Noodles #345',
    brand: 'Wei Lih',
    spicinessLevel: 5,
    originCountry: 'taiwan',
    rating: 6,
    category: 'Curry Noodles',
  },
  {
    name: 'Mama Rice Noodles #346',
    brand: 'Mama',
    spicinessLevel: 3,
    originCountry: 'china',
    rating: 10,
    category: 'Rice Noodles',
  },
  {
    name: 'Vifon Cup Noodles #347',
    brand: 'Vifon',
    spicinessLevel: 1,
    originCountry: 'singapore',
    rating: 5,
    category: 'Cup Noodles',
  },
  {
    name: 'Maggi Instant Udon #348',
    brand: 'Maggi',
    spicinessLevel: 4,
    originCountry: 'thailand',
    rating: 7,
    category: 'Instant Udon',
  },
  {
    name: 'Vifon Soba #349',
    brand: 'Vifon',
    spicinessLevel: 3,
    originCountry: 'taiwan',
    rating: 6,
    category: 'Soba',
  },
  {
    name: 'Mama Rice Noodles #350',
    brand: 'Mama',
    spicinessLevel: 5,
    originCountry: 'china',
    rating: 10,
    category: 'Rice Noodles',
  },
  {
    name: 'Wai Wai Rice Noodles #351',
    brand: 'Wai Wai',
    spicinessLevel: 4,
    originCountry: 'japan',
    rating: 7,
    category: 'Rice Noodles',
  },
  {
    name: 'Maggi Fried Noodles #352',
    brand: 'Maggi',
    spicinessLevel: 1,
    originCountry: 'indonesia',
    rating: 7,
    category: 'Fried Noodles',
  },
  {
    name: 'Vifon Tom Yum #353',
    brand: 'Vifon',
    spicinessLevel: 3,
    originCountry: 'thailand',
    rating: 6,
    category: 'Tom Yum',
  },
  {
    name: 'Mama Tom Yum #354',
    brand: 'Mama',
    spicinessLevel: 5,
    originCountry: 'china',
    rating: 6,
    category: 'Tom Yum',
  },
  {
    name: 'Ottogi Fried Noodles #355',
    brand: 'Ottogi',
    spicinessLevel: 3,
    originCountry: 'china',
    rating: 7,
    category: 'Fried Noodles',
  },
  {
    name: 'Mama Fried Noodles #356',
    brand: 'Mama',
    spicinessLevel: 2,
    originCountry: 'singapore',
    rating: 8,
    category: 'Fried Noodles',
  },
  {
    name: 'Koka Instant Udon #357',
    brand: 'Koka',
    spicinessLevel: 1,
    originCountry: 'malaysia',
    rating: 10,
    category: 'Instant Udon',
  },
  {
    name: 'Maggi Laksa #358',
    brand: 'Maggi',
    spicinessLevel: 5,
    originCountry: 'indonesia',
    rating: 9,
    category: 'Laksa',
  },
  {
    name: 'Nissin Tom Yum #359',
    brand: 'Nissin',
    spicinessLevel: 1,
    originCountry: 'philippines',
    rating: 10,
    category: 'Tom Yum',
  },
  {
    name: 'Indomie Cup Noodles #360',
    brand: 'Indomie',
    spicinessLevel: 5,
    originCountry: 'japan',
    rating: 5,
    category: 'Cup Noodles',
  },
  {
    name: 'Paldo Curry Noodles #361',
    brand: 'Paldo',
    spicinessLevel: 1,
    originCountry: 'indonesia',
    rating: 10,
    category: 'Curry Noodles',
  },
  {
    name: 'Maggi Spicy Ramen #362',
    brand: 'Maggi',
    spicinessLevel: 3,
    originCountry: 'indonesia',
    rating: 8,
    category: 'Spicy Ramen',
  },
  {
    name: 'Samyang Fried Noodles #363',
    brand: 'Samyang',
    spicinessLevel: 4,
    originCountry: 'japan',
    rating: 7,
    category: 'Fried Noodles',
  },
  {
    name: 'Nissin Fried Noodles #364',
    brand: 'Nissin',
    spicinessLevel: 5,
    originCountry: 'south_korea',
    rating: 10,
    category: 'Fried Noodles',
  },
  {
    name: 'Koka Tom Yum #365',
    brand: 'Koka',
    spicinessLevel: 5,
    originCountry: 'indonesia',
    rating: 9,
    category: 'Tom Yum',
  },
  {
    name: 'Wei Lih Laksa #366',
    brand: 'Wei Lih',
    spicinessLevel: 5,
    originCountry: 'taiwan',
    rating: 5,
    category: 'Laksa',
  },
  {
    name: 'Samyang Curry Noodles #367',
    brand: 'Samyang',
    spicinessLevel: 2,
    originCountry: 'taiwan',
    rating: 10,
    category: 'Curry Noodles',
  },
  {
    name: 'Indomie Rice Noodles #368',
    brand: 'Indomie',
    spicinessLevel: 4,
    originCountry: 'malaysia',
    rating: 9,
    category: 'Rice Noodles',
  },
  {
    name: 'Maruchan Soba #369',
    brand: 'Maruchan',
    spicinessLevel: 1,
    originCountry: 'china',
    rating: 6,
    category: 'Soba',
  },
  {
    name: 'Wei Lih Cup Noodles #370',
    brand: 'Wei Lih',
    spicinessLevel: 1,
    originCountry: 'indonesia',
    rating: 6,
    category: 'Cup Noodles',
  },
  {
    name: 'Koka Cup Noodles #371',
    brand: 'Koka',
    spicinessLevel: 4,
    originCountry: 'philippines',
    rating: 7,
    category: 'Cup Noodles',
  },
  {
    name: 'Wei Lih Tom Yum #372',
    brand: 'Wei Lih',
    spicinessLevel: 2,
    originCountry: 'singapore',
    rating: 6,
    category: 'Tom Yum',
  },
  {
    name: 'Tao Kae Noi Laksa #373',
    brand: 'Tao Kae Noi',
    spicinessLevel: 2,
    originCountry: 'indonesia',
    rating: 8,
    category: 'Laksa',
  },
  {
    name: 'Nissin Instant Udon #374',
    brand: 'Nissin',
    spicinessLevel: 3,
    originCountry: 'malaysia',
    rating: 9,
    category: 'Instant Udon',
  },
  {
    name: 'Nissin Soba #375',
    brand: 'Nissin',
    spicinessLevel: 1,
    originCountry: 'singapore',
    rating: 10,
    category: 'Soba',
  },
  {
    name: 'Nongshim Tom Yum #376',
    brand: 'Nongshim',
    spicinessLevel: 3,
    originCountry: 'vietnam',
    rating: 5,
    category: 'Tom Yum',
  },
  {
    name: 'Koka Ramen #377',
    brand: 'Koka',
    spicinessLevel: 2,
    originCountry: 'japan',
    rating: 10,
    category: 'Ramen',
  },
  {
    name: "Ching's Secret Cup Noodles #378",
    brand: "Ching's Secret",
    spicinessLevel: 5,
    originCountry: 'thailand',
    rating: 10,
    category: 'Cup Noodles',
  },
  {
    name: 'Paldo Instant Udon #379',
    brand: 'Paldo',
    spicinessLevel: 4,
    originCountry: 'vietnam',
    rating: 7,
    category: 'Instant Udon',
  },
  {
    name: 'Indomie Soba #380',
    brand: 'Indomie',
    spicinessLevel: 1,
    originCountry: 'thailand',
    rating: 5,
    category: 'Soba',
  },
  {
    name: 'Paldo Rice Noodles #381',
    brand: 'Paldo',
    spicinessLevel: 5,
    originCountry: 'china',
    rating: 10,
    category: 'Rice Noodles',
  },
  {
    name: 'Indomie Ramen #382',
    brand: 'Indomie',
    spicinessLevel: 2,
    originCountry: 'japan',
    rating: 6,
    category: 'Ramen',
  },
  {
    name: 'Paldo Soba #383',
    brand: 'Paldo',
    spicinessLevel: 2,
    originCountry: 'vietnam',
    rating: 9,
    category: 'Soba',
  },
  {
    name: "Ching's Secret Curry Noodles #384",
    brand: "Ching's Secret",
    spicinessLevel: 2,
    originCountry: 'malaysia',
    rating: 6,
    category: 'Curry Noodles',
  },
  {
    name: 'Koka Laksa #385',
    brand: 'Koka',
    spicinessLevel: 4,
    originCountry: 'thailand',
    rating: 7,
    category: 'Laksa',
  },
  {
    name: 'Wei Lih Laksa #386',
    brand: 'Wei Lih',
    spicinessLevel: 1,
    originCountry: 'taiwan',
    rating: 9,
    category: 'Laksa',
  },
  {
    name: 'Tao Kae Noi Instant Udon #387',
    brand: 'Tao Kae Noi',
    spicinessLevel: 3,
    originCountry: 'south_korea',
    rating: 8,
    category: 'Instant Udon',
  },
  {
    name: 'Nongshim Cup Noodles #388',
    brand: 'Nongshim',
    spicinessLevel: 3,
    originCountry: 'malaysia',
    rating: 6,
    category: 'Cup Noodles',
  },
  {
    name: 'Vifon Laksa #389',
    brand: 'Vifon',
    spicinessLevel: 4,
    originCountry: 'vietnam',
    rating: 6,
    category: 'Laksa',
  },
  {
    name: 'Indomie Curry Noodles #390',
    brand: 'Indomie',
    spicinessLevel: 4,
    originCountry: 'thailand',
    rating: 10,
    category: 'Curry Noodles',
  },
  {
    name: 'Indomie Ramen #391',
    brand: 'Indomie',
    spicinessLevel: 3,
    originCountry: 'japan',
    rating: 9,
    category: 'Ramen',
  },
  {
    name: 'Mama Laksa #392',
    brand: 'Mama',
    spicinessLevel: 4,
    originCountry: 'taiwan',
    rating: 9,
    category: 'Laksa',
  },
  {
    name: "Ching's Secret Laksa #393",
    brand: "Ching's Secret",
    spicinessLevel: 2,
    originCountry: 'taiwan',
    rating: 8,
    category: 'Laksa',
  },
  {
    name: 'Mama Soba #394',
    brand: 'Mama',
    spicinessLevel: 1,
    originCountry: 'malaysia',
    rating: 7,
    category: 'Soba',
  },
  {
    name: 'Paldo Tom Yum #395',
    brand: 'Paldo',
    spicinessLevel: 5,
    originCountry: 'south_korea',
    rating: 6,
    category: 'Tom Yum',
  },
  {
    name: 'Tao Kae Noi Instant Udon #396',
    brand: 'Tao Kae Noi',
    spicinessLevel: 5,
    originCountry: 'taiwan',
    rating: 7,
    category: 'Instant Udon',
  },
  {
    name: 'Mama Ramen #397',
    brand: 'Mama',
    spicinessLevel: 1,
    originCountry: 'japan',
    rating: 7,
    category: 'Ramen',
  },
  {
    name: 'Mama Spicy Ramen #398',
    brand: 'Mama',
    spicinessLevel: 4,
    originCountry: 'malaysia',
    rating: 5,
    category: 'Spicy Ramen',
  },
  {
    name: 'Maggi Cup Noodles #399',
    brand: 'Maggi',
    spicinessLevel: 5,
    originCountry: 'philippines',
    rating: 10,
    category: 'Cup Noodles',
  },
  {
    name: 'Mama Spicy Ramen #400',
    brand: 'Mama',
    spicinessLevel: 1,
    originCountry: 'indonesia',
    rating: 5,
    category: 'Spicy Ramen',
  },
  {
    name: 'Vifon Rice Noodles #401',
    brand: 'Vifon',
    spicinessLevel: 1,
    originCountry: 'taiwan',
    rating: 9,
    category: 'Rice Noodles',
  },
  {
    name: 'Mama Cup Noodles #402',
    brand: 'Mama',
    spicinessLevel: 4,
    originCountry: 'japan',
    rating: 8,
    category: 'Cup Noodles',
  },
  {
    name: 'Maggi Rice Noodles #403',
    brand: 'Maggi',
    spicinessLevel: 2,
    originCountry: 'china',
    rating: 6,
    category: 'Rice Noodles',
  },
  {
    name: 'Maruchan Curry Noodles #404',
    brand: 'Maruchan',
    spicinessLevel: 3,
    originCountry: 'japan',
    rating: 6,
    category: 'Curry Noodles',
  },
  {
    name: 'Maggi Laksa #405',
    brand: 'Maggi',
    spicinessLevel: 2,
    originCountry: 'taiwan',
    rating: 9,
    category: 'Laksa',
  },
  {
    name: 'Mama Cup Noodles #406',
    brand: 'Mama',
    spicinessLevel: 3,
    originCountry: 'thailand',
    rating: 10,
    category: 'Cup Noodles',
  },
  {
    name: 'Indomie Soba #407',
    brand: 'Indomie',
    spicinessLevel: 5,
    originCountry: 'taiwan',
    rating: 5,
    category: 'Soba',
  },
  {
    name: 'Nongshim Fried Noodles #408',
    brand: 'Nongshim',
    spicinessLevel: 2,
    originCountry: 'singapore',
    rating: 10,
    category: 'Fried Noodles',
  },
  {
    name: 'Maggi Spicy Ramen #409',
    brand: 'Maggi',
    spicinessLevel: 2,
    originCountry: 'indonesia',
    rating: 9,
    category: 'Spicy Ramen',
  },
  {
    name: 'Ottogi Tom Yum #410',
    brand: 'Ottogi',
    spicinessLevel: 4,
    originCountry: 'japan',
    rating: 9,
    category: 'Tom Yum',
  },
  {
    name: 'Maggi Fried Noodles #411',
    brand: 'Maggi',
    spicinessLevel: 3,
    originCountry: 'taiwan',
    rating: 9,
    category: 'Fried Noodles',
  },
  {
    name: 'Nissin Laksa #412',
    brand: 'Nissin',
    spicinessLevel: 1,
    originCountry: 'taiwan',
    rating: 6,
    category: 'Laksa',
  },
  {
    name: "Ching's Secret Soba #413",
    brand: "Ching's Secret",
    spicinessLevel: 1,
    originCountry: 'singapore',
    rating: 5,
    category: 'Soba',
  },
  {
    name: 'Maggi Ramen #414',
    brand: 'Maggi',
    spicinessLevel: 4,
    originCountry: 'philippines',
    rating: 5,
    category: 'Ramen',
  },
  {
    name: 'Wai Wai Spicy Ramen #415',
    brand: 'Wai Wai',
    spicinessLevel: 4,
    originCountry: 'japan',
    rating: 6,
    category: 'Spicy Ramen',
  },
  {
    name: 'Wai Wai Laksa #416',
    brand: 'Wai Wai',
    spicinessLevel: 5,
    originCountry: 'malaysia',
    rating: 5,
    category: 'Laksa',
  },
  {
    name: 'Samyang Cup Noodles #417',
    brand: 'Samyang',
    spicinessLevel: 3,
    originCountry: 'china',
    rating: 6,
    category: 'Cup Noodles',
  },
  {
    name: 'Wei Lih Cup Noodles #418',
    brand: 'Wei Lih',
    spicinessLevel: 4,
    originCountry: 'taiwan',
    rating: 5,
    category: 'Cup Noodles',
  },
  {
    name: 'Vifon Instant Udon #419',
    brand: 'Vifon',
    spicinessLevel: 2,
    originCountry: 'thailand',
    rating: 10,
    category: 'Instant Udon',
  },
  {
    name: 'Nongshim Spicy Ramen #420',
    brand: 'Nongshim',
    spicinessLevel: 5,
    originCountry: 'south_korea',
    rating: 9,
    category: 'Spicy Ramen',
  },
  {
    name: "Ching's Secret Soba #421",
    brand: "Ching's Secret",
    spicinessLevel: 2,
    originCountry: 'philippines',
    rating: 9,
    category: 'Soba',
  },
  {
    name: 'Mama Instant Udon #422',
    brand: 'Mama',
    spicinessLevel: 3,
    originCountry: 'thailand',
    rating: 5,
    category: 'Instant Udon',
  },
  {
    name: 'Indomie Curry Noodles #423',
    brand: 'Indomie',
    spicinessLevel: 1,
    originCountry: 'indonesia',
    rating: 10,
    category: 'Curry Noodles',
  },
  {
    name: 'MyKuali Fried Noodles #424',
    brand: 'MyKuali',
    spicinessLevel: 5,
    originCountry: 'malaysia',
    rating: 6,
    category: 'Fried Noodles',
  },
  {
    name: 'Tao Kae Noi Soba #425',
    brand: 'Tao Kae Noi',
    spicinessLevel: 5,
    originCountry: 'philippines',
    rating: 6,
    category: 'Soba',
  },
  {
    name: 'Acecook Tom Yum #426',
    brand: 'Acecook',
    spicinessLevel: 3,
    originCountry: 'taiwan',
    rating: 7,
    category: 'Tom Yum',
  },
  {
    name: "Ching's Secret Spicy Ramen #427",
    brand: "Ching's Secret",
    spicinessLevel: 4,
    originCountry: 'vietnam',
    rating: 7,
    category: 'Spicy Ramen',
  },
  {
    name: 'Mama Rice Noodles #428',
    brand: 'Mama',
    spicinessLevel: 5,
    originCountry: 'indonesia',
    rating: 6,
    category: 'Rice Noodles',
  },
  {
    name: 'Wei Lih Instant Udon #429',
    brand: 'Wei Lih',
    spicinessLevel: 2,
    originCountry: 'china',
    rating: 6,
    category: 'Instant Udon',
  },
  {
    name: 'Paldo Cup Noodles #430',
    brand: 'Paldo',
    spicinessLevel: 1,
    originCountry: 'japan',
    rating: 6,
    category: 'Cup Noodles',
  },
  {
    name: 'Knorr Rice Noodles #431',
    brand: 'Knorr',
    spicinessLevel: 2,
    originCountry: 'indonesia',
    rating: 8,
    category: 'Rice Noodles',
  },
  {
    name: 'Vifon Laksa #432',
    brand: 'Vifon',
    spicinessLevel: 1,
    originCountry: 'malaysia',
    rating: 6,
    category: 'Laksa',
  },
  {
    name: 'Knorr Fried Noodles #433',
    brand: 'Knorr',
    spicinessLevel: 3,
    originCountry: 'vietnam',
    rating: 10,
    category: 'Fried Noodles',
  },
  {
    name: 'Nissin Spicy Ramen #434',
    brand: 'Nissin',
    spicinessLevel: 3,
    originCountry: 'vietnam',
    rating: 5,
    category: 'Spicy Ramen',
  },
  {
    name: 'MyKuali Spicy Ramen #435',
    brand: 'MyKuali',
    spicinessLevel: 2,
    originCountry: 'south_korea',
    rating: 9,
    category: 'Spicy Ramen',
  },
  {
    name: 'Maggi Rice Noodles #436',
    brand: 'Maggi',
    spicinessLevel: 5,
    originCountry: 'indonesia',
    rating: 8,
    category: 'Rice Noodles',
  },
  {
    name: 'Koka Soba #437',
    brand: 'Koka',
    spicinessLevel: 3,
    originCountry: 'taiwan',
    rating: 7,
    category: 'Soba',
  },
  {
    name: 'Koka Ramen #438',
    brand: 'Koka',
    spicinessLevel: 2,
    originCountry: 'thailand',
    rating: 5,
    category: 'Ramen',
  },
  {
    name: 'Mama Laksa #439',
    brand: 'Mama',
    spicinessLevel: 2,
    originCountry: 'vietnam',
    rating: 5,
    category: 'Laksa',
  },
  {
    name: 'MyKuali Ramen #440',
    brand: 'MyKuali',
    spicinessLevel: 3,
    originCountry: 'indonesia',
    rating: 6,
    category: 'Ramen',
  },
  {
    name: 'Nissin Tom Yum #441',
    brand: 'Nissin',
    spicinessLevel: 2,
    originCountry: 'taiwan',
    rating: 7,
    category: 'Tom Yum',
  },
  {
    name: 'Koka Spicy Ramen #442',
    brand: 'Koka',
    spicinessLevel: 4,
    originCountry: 'vietnam',
    rating: 10,
    category: 'Spicy Ramen',
  },
  {
    name: 'Samyang Laksa #443',
    brand: 'Samyang',
    spicinessLevel: 2,
    originCountry: 'malaysia',
    rating: 5,
    category: 'Laksa',
  },
  {
    name: 'Maruchan Fried Noodles #444',
    brand: 'Maruchan',
    spicinessLevel: 4,
    originCountry: 'china',
    rating: 6,
    category: 'Fried Noodles',
  },
  {
    name: 'Maggi Spicy Ramen #445',
    brand: 'Maggi',
    spicinessLevel: 1,
    originCountry: 'singapore',
    rating: 9,
    category: 'Spicy Ramen',
  },
  {
    name: "Ching's Secret Spicy Ramen #446",
    brand: "Ching's Secret",
    spicinessLevel: 3,
    originCountry: 'thailand',
    rating: 5,
    category: 'Spicy Ramen',
  },
  {
    name: "Ching's Secret Curry Noodles #447",
    brand: "Ching's Secret",
    spicinessLevel: 5,
    originCountry: 'singapore',
    rating: 10,
    category: 'Curry Noodles',
  },
  {
    name: 'Ottogi Soba #448',
    brand: 'Ottogi',
    spicinessLevel: 3,
    originCountry: 'malaysia',
    rating: 9,
    category: 'Soba',
  },
  {
    name: 'Maruchan Cup Noodles #449',
    brand: 'Maruchan',
    spicinessLevel: 1,
    originCountry: 'south_korea',
    rating: 8,
    category: 'Cup Noodles',
  },
  {
    name: 'MyKuali Cup Noodles #450',
    brand: 'MyKuali',
    spicinessLevel: 4,
    originCountry: 'south_korea',
    rating: 5,
    category: 'Cup Noodles',
  },
  {
    name: 'Mama Rice Noodles #451',
    brand: 'Mama',
    spicinessLevel: 2,
    originCountry: 'malaysia',
    rating: 10,
    category: 'Rice Noodles',
  },
  {
    name: 'Wei Lih Rice Noodles #452',
    brand: 'Wei Lih',
    spicinessLevel: 4,
    originCountry: 'malaysia',
    rating: 9,
    category: 'Rice Noodles',
  },
  {
    name: 'Nissin Fried Noodles #453',
    brand: 'Nissin',
    spicinessLevel: 3,
    originCountry: 'thailand',
    rating: 9,
    category: 'Fried Noodles',
  },
  {
    name: 'Nongshim Instant Udon #454',
    brand: 'Nongshim',
    spicinessLevel: 3,
    originCountry: 'china',
    rating: 9,
    category: 'Instant Udon',
  },
  {
    name: 'Maggi Spicy Ramen #455',
    brand: 'Maggi',
    spicinessLevel: 3,
    originCountry: 'china',
    rating: 5,
    category: 'Spicy Ramen',
  },
  {
    name: 'Mama Cup Noodles #456',
    brand: 'Mama',
    spicinessLevel: 1,
    originCountry: 'taiwan',
    rating: 5,
    category: 'Cup Noodles',
  },
  {
    name: 'Wei Lih Spicy Ramen #457',
    brand: 'Wei Lih',
    spicinessLevel: 3,
    originCountry: 'thailand',
    rating: 6,
    category: 'Spicy Ramen',
  },
  {
    name: "Ching's Secret Instant Udon #458",
    brand: "Ching's Secret",
    spicinessLevel: 3,
    originCountry: 'singapore',
    rating: 5,
    category: 'Instant Udon',
  },
  {
    name: 'Mama Soba #459',
    brand: 'Mama',
    spicinessLevel: 1,
    originCountry: 'indonesia',
    rating: 7,
    category: 'Soba',
  },
  {
    name: 'Tao Kae Noi Spicy Ramen #460',
    brand: 'Tao Kae Noi',
    spicinessLevel: 4,
    originCountry: 'indonesia',
    rating: 8,
    category: 'Spicy Ramen',
  },
  {
    name: 'MyKuali Curry Noodles #461',
    brand: 'MyKuali',
    spicinessLevel: 4,
    originCountry: 'indonesia',
    rating: 6,
    category: 'Curry Noodles',
  },
  {
    name: 'Samyang Rice Noodles #462',
    brand: 'Samyang',
    spicinessLevel: 2,
    originCountry: 'japan',
    rating: 9,
    category: 'Rice Noodles',
  },
  {
    name: 'Maggi Tom Yum #463',
    brand: 'Maggi',
    spicinessLevel: 4,
    originCountry: 'japan',
    rating: 6,
    category: 'Tom Yum',
  },
  {
    name: 'Vifon Curry Noodles #464',
    brand: 'Vifon',
    spicinessLevel: 1,
    originCountry: 'south_korea',
    rating: 5,
    category: 'Curry Noodles',
  },
  {
    name: 'Nongshim Instant Udon #465',
    brand: 'Nongshim',
    spicinessLevel: 4,
    originCountry: 'china',
    rating: 7,
    category: 'Instant Udon',
  },
  {
    name: 'MyKuali Rice Noodles #466',
    brand: 'MyKuali',
    spicinessLevel: 4,
    originCountry: 'taiwan',
    rating: 8,
    category: 'Rice Noodles',
  },
  {
    name: 'Indomie Ramen #467',
    brand: 'Indomie',
    spicinessLevel: 1,
    originCountry: 'china',
    rating: 9,
    category: 'Ramen',
  },
  {
    name: 'Wei Lih Laksa #468',
    brand: 'Wei Lih',
    spicinessLevel: 3,
    originCountry: 'japan',
    rating: 9,
    category: 'Laksa',
  },
  {
    name: 'Koka Instant Udon #469',
    brand: 'Koka',
    spicinessLevel: 5,
    originCountry: 'malaysia',
    rating: 8,
    category: 'Instant Udon',
  },
  {
    name: 'Maggi Soba #470',
    brand: 'Maggi',
    spicinessLevel: 4,
    originCountry: 'philippines',
    rating: 9,
    category: 'Soba',
  },
  {
    name: "Ching's Secret Rice Noodles #471",
    brand: "Ching's Secret",
    spicinessLevel: 5,
    originCountry: 'singapore',
    rating: 10,
    category: 'Rice Noodles',
  },
  {
    name: 'Knorr Spicy Ramen #472',
    brand: 'Knorr',
    spicinessLevel: 1,
    originCountry: 'singapore',
    rating: 10,
    category: 'Spicy Ramen',
  },
  {
    name: 'Mama Fried Noodles #473',
    brand: 'Mama',
    spicinessLevel: 1,
    originCountry: 'japan',
    rating: 7,
    category: 'Fried Noodles',
  },
  {
    name: 'Samyang Rice Noodles #474',
    brand: 'Samyang',
    spicinessLevel: 4,
    originCountry: 'thailand',
    rating: 8,
    category: 'Rice Noodles',
  },
  {
    name: 'Maggi Instant Udon #475',
    brand: 'Maggi',
    spicinessLevel: 3,
    originCountry: 'philippines',
    rating: 6,
    category: 'Instant Udon',
  },
  {
    name: 'MyKuali Cup Noodles #476',
    brand: 'MyKuali',
    spicinessLevel: 5,
    originCountry: 'philippines',
    rating: 6,
    category: 'Cup Noodles',
  },
  {
    name: 'Paldo Ramen #477',
    brand: 'Paldo',
    spicinessLevel: 3,
    originCountry: 'philippines',
    rating: 7,
    category: 'Ramen',
  },
  {
    name: 'Mama Instant Udon #478',
    brand: 'Mama',
    spicinessLevel: 2,
    originCountry: 'china',
    rating: 5,
    category: 'Instant Udon',
  },
  {
    name: 'Wai Wai Ramen #479',
    brand: 'Wai Wai',
    spicinessLevel: 5,
    originCountry: 'china',
    rating: 8,
    category: 'Ramen',
  },
  {
    name: 'Acecook Soba #480',
    brand: 'Acecook',
    spicinessLevel: 2,
    originCountry: 'malaysia',
    rating: 10,
    category: 'Soba',
  },
  {
    name: 'Nissin Fried Noodles #481',
    brand: 'Nissin',
    spicinessLevel: 2,
    originCountry: 'malaysia',
    rating: 6,
    category: 'Fried Noodles',
  },
  {
    name: 'Vifon Cup Noodles #482',
    brand: 'Vifon',
    spicinessLevel: 4,
    originCountry: 'philippines',
    rating: 7,
    category: 'Cup Noodles',
  },
  {
    name: 'Acecook Ramen #483',
    brand: 'Acecook',
    spicinessLevel: 3,
    originCountry: 'vietnam',
    rating: 7,
    category: 'Ramen',
  },
  {
    name: 'Maruchan Fried Noodles #484',
    brand: 'Maruchan',
    spicinessLevel: 2,
    originCountry: 'malaysia',
    rating: 10,
    category: 'Fried Noodles',
  },
  {
    name: 'Paldo Spicy Ramen #485',
    brand: 'Paldo',
    spicinessLevel: 4,
    originCountry: 'indonesia',
    rating: 8,
    category: 'Spicy Ramen',
  },
  {
    name: 'Vifon Spicy Ramen #486',
    brand: 'Vifon',
    spicinessLevel: 3,
    originCountry: 'thailand',
    rating: 9,
    category: 'Spicy Ramen',
  },
  {
    name: 'Acecook Laksa #487',
    brand: 'Acecook',
    spicinessLevel: 3,
    originCountry: 'taiwan',
    rating: 7,
    category: 'Laksa',
  },
  {
    name: 'Mama Fried Noodles #488',
    brand: 'Mama',
    spicinessLevel: 5,
    originCountry: 'thailand',
    rating: 10,
    category: 'Fried Noodles',
  },
  {
    name: 'Vifon Cup Noodles #489',
    brand: 'Vifon',
    spicinessLevel: 5,
    originCountry: 'thailand',
    rating: 9,
    category: 'Cup Noodles',
  },
  {
    name: 'Knorr Tom Yum #490',
    brand: 'Knorr',
    spicinessLevel: 2,
    originCountry: 'vietnam',
    rating: 5,
    category: 'Tom Yum',
  },
  {
    name: 'Indomie Rice Noodles #491',
    brand: 'Indomie',
    spicinessLevel: 5,
    originCountry: 'malaysia',
    rating: 5,
    category: 'Rice Noodles',
  },
  {
    name: 'Ottogi Curry Noodles #492',
    brand: 'Ottogi',
    spicinessLevel: 4,
    originCountry: 'china',
    rating: 7,
    category: 'Curry Noodles',
  },
  {
    name: 'Samyang Laksa #493',
    brand: 'Samyang',
    spicinessLevel: 2,
    originCountry: 'thailand',
    rating: 6,
    category: 'Laksa',
  },
  {
    name: 'Samyang Fried Noodles #494',
    brand: 'Samyang',
    spicinessLevel: 4,
    originCountry: 'indonesia',
    rating: 10,
    category: 'Fried Noodles',
  },
  {
    name: 'Maggi Laksa #495',
    brand: 'Maggi',
    spicinessLevel: 5,
    originCountry: 'philippines',
    rating: 8,
    category: 'Laksa',
  },
  {
    name: 'Wei Lih Ramen #496',
    brand: 'Wei Lih',
    spicinessLevel: 5,
    originCountry: 'thailand',
    rating: 8,
    category: 'Ramen',
  },
  {
    name: 'Wei Lih Laksa #497',
    brand: 'Wei Lih',
    spicinessLevel: 1,
    originCountry: 'thailand',
    rating: 7,
    category: 'Laksa',
  },
  {
    name: 'Mama Ramen #498',
    brand: 'Mama',
    spicinessLevel: 1,
    originCountry: 'south_korea',
    rating: 8,
    category: 'Ramen',
  },
  {
    name: 'Wei Lih Tom Yum #499',
    brand: 'Wei Lih',
    spicinessLevel: 4,
    originCountry: 'philippines',
    rating: 7,
    category: 'Tom Yum',
  },
  {
    name: "Ching's Secret Curry Noodles #500",
    brand: "Ching's Secret",
    spicinessLevel: 5,
    originCountry: 'japan',
    rating: 7,
    category: 'Curry Noodles',
  },
];

export default noodles;
